// ==UserScript==
// @name                WME Klang Valley MapRaid June 2016 Overlay
// @namespace           https://greasyfork.org/users/5252
// @description         Creates polygons for MapRaid groups in a WME "Klang Valley MapRaid June 2016 Groups" layer
// @include             https://www.waze.com/editor/*
// @include             https://www.waze.com/*/editor/*
// @include             https://editor-beta.waze.com/*
// @version             2.4
// @grant               none
// @copyright           2014 davielde
// ==/UserScript==


//---------------------------------------------------------------------------------------


//generated by rickzabel's overlay generator

//RZ RaidName will be replaced by the name of the layer in your KML file
//RZ RaidNameNoSpaces will be replaced by the name of the layer in your KML file
//RZ AreaPoints will be replaced by the names, colors, and area points from your KML file

setTimeout(InitMapRaidOverlay, 1000);

function AddRaidPolygon(raidLayer,groupPoints,groupColor,groupNumber){
    
    var mro_Map = Waze.map;
    var mro_OL = OpenLayers;
    var raidGroupLabel = 'Raid Group ' + groupNumber;
    var groupName = 'RaidGroup' + groupNumber;
    
    var style = {
        strokeColor: groupColor,
        strokeOpacity: .8,
        strokeWidth: 3,
        fillColor: groupColor,
        fillOpacity: 0.15,
        label: raidGroupLabel,
        labelOutlineColor: "black",
        labelOutlineWidth: 3,
        fontSize: 14,
        fontColor: groupColor,
        fontOpacity: .85,
        fontWeight: "bold"  
    };
    
    var attributes = {
        name: groupName,
        number: groupNumber
    };
    
    var pnt= [];
    for(i=0;i<groupPoints.length;i++){
        convPoint = new OpenLayers.Geometry.Point(groupPoints[i].lon,groupPoints[i].lat).transform(new OpenLayers.Projection("EPSG:4326"), mro_Map.getProjectionObject());
        //console.log('MapRaid: ' + JSON.stringify(groupPoints[i]) + ', ' + groupPoints[i].lon + ', ' + groupPoints[i].lat);
        pnt.push(convPoint);
    }
		       
    var ring = new mro_OL.Geometry.LinearRing(pnt);
    var polygon = new mro_OL.Geometry.Polygon([ring]);
    
    var feature = new mro_OL.Feature.Vector(polygon,attributes,style);
    raidLayer.addFeatures([feature]);

}

function CurrentRaidLocation(raid_mapLayer){
    var mro_Map = Waze.map;

    for(i=0;i<raid_mapLayer.features.length;i++){
        var raidMapCenter = mro_Map.getCenter();
        var raidCenterPoint = new OpenLayers.Geometry.Point(raidMapCenter.lon,raidMapCenter.lat);
        var raidCenterCheck = raid_mapLayer.features[i].geometry.components[0].containsPoint(raidCenterPoint);
		var holes = raid_mapLayer.features[i].attributes.holes;
		
        
        if(raidCenterCheck === true){

			//var str = $('#topbar-container > div > div.location-info-region > div').text();
			var str = $('#topbar-container > div > div.topbar > div.location-info-region > div.location-info').text();
			var n2 = str.indexOf(" - ");
			
			if(n2 > 0){
				var n = str.length;
				var res = str.substring(n2+2, n);
				var rescount = res.indexOf(" - ");
				if(rescount>0){
					var n3 = res.length;
					var res2 = res.substring(rescount+2, n3);
				}
				var raidLocationLabel = '[Raid Group - ' + raid_mapLayer.features[i].attributes.number + '] - ' + res2;

			} else {
				//var raidLocationLabel = '[Raid Group - ' + raid_mapLayer.features[i].attributes.number + '] - ' + $('#topbar-container > div > div.location-info-region > div').text();
				var raidLocationLabel = '[Raid Group - ' + raid_mapLayer.features[i].attributes.number + '] - ' + $('#topbar-container > div > div.topbar > div.location-info-region > div.location-info').text();		
			}	
			//setTimeout(function(){$('#topbar-container > div > div.location-info-region > div').text(raidLocationLabel);},200);
			setTimeout(function(){$('#topbar-container > div > div.topbar > div.location-info-region > div.location-info').text(raidLocationLabel);},200);
			 if (holes === "false") { break; }
		}
    }
}

function InitMapRaidOverlay(){

    var mro_Map = Waze.map;
    var mro_OL = OpenLayers;

    //if (!mro_Map) return;
	
    //if (!mro_OL) return;

    var mro_mapLayers = mro_Map.getLayersBy("uniqueName","__KlangValleyMapRaidJune2016");
        
    var raid_mapLayer = new mro_OL.Layer.Vector("Klang Valley MapRaid June 2016", {
        displayInLayerSwitcher: true,
        uniqueName: "__KlangValleyMapRaidJune2016"
    });
        
    I18n.translations.en.layers.name["__KlangValleyMapRaidJune2016"] = "Klang Valley MapRaid June 2016";
    mro_Map.addLayer(raid_mapLayer);
    raid_mapLayer.setVisibility(true);
    

var VArea01&amp;06 = [{lon:'101.1087226',lat:'3.4606472'},{lon:'101.1869245',lat:'3.3451503'},{lon:'101.2953186',lat:'3.2502086'},{lon:'101.2980652',lat:'3.2299849'},{lon:'101.3025284',lat:'3.1946782'},{lon:'101.3020135',lat:'3.1717109'},{lon:'101.3049317',lat:'3.1497719'},{lon:'101.3084508',lat:'3.1311745'},{lon:'101.1791039',lat:'3.0021844'},{lon:'101.2437255',lat:'2.8169539'},{lon:'101.4833945',lat:'2.7860408'},{lon:'101.6238447',lat:'2.8021227'},{lon:'101.5253448',lat:'3.1240613'},{lon:'101.4814854',lat:'3.3082208'},{lon:'101.4381899',lat:'3.4985549'},{lon:'101.3749694',lat:'3.490804'},{lon:'101.3296509',lat:'3.4860065'},{lon:'101.2541199',lat:'3.4784673'},{lon:'101.1087226',lat:'3.4606472'}];
AddRaidPolygon(raid_mapLayer, VArea01&amp;06,"#DB4436","Area 01 &amp; 06");

var VArea02&amp;07 = [{lon:'101.4381899',lat:'3.4985549'},{lon:'101.5248298',lat:'3.1321173'},{lon:'101.5734006',lat:'2.9665211'},{lon:'101.6238447',lat:'2.8021227'},{lon:'101.7581177',lat:'2.8288594'},{lon:'101.7352331',lat:'2.9016012'},{lon:'101.725678',lat:'2.9381434'},{lon:'101.7150923',lat:'2.9739999'},{lon:'101.6701516',lat:'3.133357'},{lon:'101.653607',lat:'3.2007857'},{lon:'101.6317388',lat:'3.3115745'},{lon:'101.5976143',lat:'3.4865205'},{lon:'101.5463736',lat:'3.4878068'},{lon:'101.5658569',lat:'3.4877198'},{lon:'101.5035439',lat:'3.4889192'},{lon:'101.4381899',lat:'3.4985549'}];
AddRaidPolygon(raid_mapLayer, VArea02&amp;07,"#4186F0","Area 02 &amp; 07");

var VArea05&amp;08 = [{lon:'101.7581177',lat:'2.8288594'},{lon:'101.953125',lat:'2.8525196'},{lon:'101.9421387',lat:'3.0157269'},{lon:'101.9634247',lat:'3.0849799'},{lon:'101.9586182',lat:'3.1624555'},{lon:'101.941452',lat:'3.234441'},{lon:'101.9071198',lat:'3.2735167'},{lon:'101.8460083',lat:'3.2995663'},{lon:'101.832962',lat:'3.3235588'},{lon:'101.811676',lat:'3.3420669'},{lon:'101.7965699',lat:'3.3660583'},{lon:'101.7855835',lat:'3.3969035'},{lon:'101.7828369',lat:'3.4277478'},{lon:'101.7725373',lat:'3.503826'},{lon:'101.714859',lat:'3.496287'},{lon:'101.7869568',lat:'3.2577495'},{lon:'101.8219757',lat:'3.1124055'},{lon:'101.7874709',lat:'3.08618'},{lon:'101.7539978',lat:'3.0602962'},{lon:'101.6942919',lat:'3.047697'},{lon:'101.73117',lat:'2.9164633'},{lon:'101.7446444',lat:'2.87249'},{lon:'101.7581177',lat:'2.8288594'}];
AddRaidPolygon(raid_mapLayer, VArea05&amp;08,"#7C3592","Area 05 &amp; 08");

var VArea03&amp;04 = [{lon:'101.5976143',lat:'3.4865205'},{lon:'101.6311803',lat:'3.3138619'},{lon:'101.6688538',lat:'3.1432586'},{lon:'101.6942919',lat:'3.047697'},{lon:'101.7539978',lat:'3.0602962'},{lon:'101.8219757',lat:'3.1124055'},{lon:'101.7842206',lat:'3.2625311'},{lon:'101.714859',lat:'3.496287'},{lon:'101.5976143',lat:'3.4865205'}];
AddRaidPolygon(raid_mapLayer, VArea03&amp;04,"#DB4436","Area 03 &amp; 04");

var VPolygon1 = [{lon:'101.1087226',lat:'3.4606472'},{lon:'101.1869245',lat:'3.3451503'},{lon:'101.2953186',lat:'3.2502086'},{lon:'101.3084508',lat:'3.1311745'},{lon:'101.1791039',lat:'3.0021844'},{lon:'101.2437255',lat:'2.8169539'},{lon:'101.4833945',lat:'2.7860408'},{lon:'101.953125',lat:'2.8525196'},{lon:'101.9421387',lat:'3.0157269'},{lon:'101.9634247',lat:'3.0849799'},{lon:'101.9613647',lat:'3.1418873'},{lon:'101.941452',lat:'3.234441'},{lon:'101.9071198',lat:'3.2735167'},{lon:'101.8460083',lat:'3.2995663'},{lon:'101.8171692',lat:'3.3324701'},{lon:'101.7897034',lat:'3.3804528'},{lon:'101.7725373',lat:'3.503826'},{lon:'101.7230988',lat:'3.4949163'},{lon:'101.5976143',lat:'3.4865205'},{lon:'101.4381899',lat:'3.4985549'},{lon:'101.1087226',lat:'3.4606472'}];
AddRaidPolygon(raid_mapLayer, VPolygon1,"#000000","Polygon 1");


    
	
	
    setTimeout(function(){CurrentRaidLocation(raid_mapLayer);},3000);
    mro_Map.events.register("moveend", Waze.map, function(){ setTimeout(function(){CurrentRaidLocation(raid_mapLayer);},1500);});
    mro_Map.events.register("zoomend", Waze.map, function(){ setTimeout(function(){CurrentRaidLocation(raid_mapLayer);},1500);});
       
       
}
