// ==UserScript==
// @name         nobody
// @namespace    https://greasyfork.org/en/scripts/bullshitmemes/
// @version      6.0964
// @description  fucking bullshit
// @match        https://plug.dj/*
// @grant        none
// @copyright    2015
// ==/UserScript==
 
//{ src:"", width:, height:, title:''},
 
var emotes = [
    { src:"http://i.imgur.com/1tME9i9.gif", width:50, height:49, title:'mako'},
    { src:"http://i.imgur.com/EOJVmvF.gif", width:53, height:55, title:'skeletal'},
    { src:"http://i.imgur.com/xv1O1si.gif", width:45, height:48, title:'ryu'},
    { src:"http://i.imgur.com/Q029MEI.gif", width:62, height:50, title:'dubass'},
    { src:"http://i.imgur.com/IcHOs.gif", width:60, height:70, title:'harahu'},
    { src:"http://i.imgur.com/B6bBva0.gif", width:50, height:51, title:'yoshi'},
    { src:"http://i.imgur.com/F5qdDtE.gif", width:125, height:45, title:'kabi'},    
    { src:"http://i.imgur.com/mkoBhqm.gif", width:55, height:65, title:'blue'},
    { src:"http://i.imgur.com/eqmUDB6.gif", width:52, height:50, title:'her'},
    { src:"http://i.imgur.com/6tqguge.gif", width:68, height:50, title:'ff6kappa'},
    { src:"http://i.imgur.com/FBcmjnJ.gif", width:75, height:43, title:'penguin'},
    { src:"http://i.imgur.com/199ZHvl.gif", width:54, height:55, title:'strut'},
    { src:"http://i.imgur.com/TGHRo8W.gif", width:54, height:55, title:'chen2'},
    { src:"http://i.imgur.com/MSoQrxX.gif", width:54, height:55, title:'chen3'},
    { src:"http://i.imgur.com/S417M86.gif", width:54, height:55, title:'buttjuice'},
    { src:"http://i.imgur.com/ELQA2fB.gif", width:54, height:55, title:'notabotnet'},
    { src:"http://i.imgur.com/HOdSCiN.gif", width:54, height:55, title:'laughinganime'},
    { src:"http://i.imgur.com/giQjsb3.gif", width:48, height:70, title:'mememe'},  
    { src:"http://i.imgur.com/7VcUcYJ.gif", width:54, height:55, title:'duckgif'},
    { src:"http://i.imgur.com/wAVQL4D.gif", width:60, height:47, title:'wop'},
    { src:"http://i.imgur.com/l1jmNIC.gif", width:60, height:47, title:'miku3'},
    { src:"http://i.imgur.com/RgnpAPE.gif", width:45, height:59, title:'ayylien'},
    { src:"http://i.imgur.com/7AyGv1a.gif", width:60, height:74, title:'ayylmao'},
    { src:"http://i.imgur.com/8WGVGYh.gif", width:35, height:59, title:'cyrax'},
    { src:"http://i.imgur.com/XNCKzV8.gif", width:40, height:60, title:'respectfulnod'},
    { src:"http://i.imgur.com/MMdhwkH.gif", width:40, height:60, title:'cry'},
    { src:"http://i.imgur.com/HWYBpFp.gif", width:44, height:75, title:'thom'},
    { src:"http://i.imgur.com/Vwq5J2n.png", width:65, height:60, title:'guts'},
    { src:"http://i.imgur.com/kauEfnn.gif", width:60, height:60, title:'marissa'},
    { src:"http://i.imgur.com/RRPNiqa.gif", width:50, height:60, title:'reimu'},
    { src:"http://i.imgur.com/c2vk6ik.gif", width:50, height:60, title:'mysides2'},
    { src:"http://i.imgur.com/4wunBBM.png", width:60, height:52, title:'slut'},
    { src:"http://i.imgur.com/Gx5wmqn.gif", width:67, height:50, title:'wow2'},
    { src:"http://i.imgur.com/nfDwcil.png", width:40, height:56, title:'gookfood'},
    { src:"http://i.imgur.com/WFHNOxP.gif", width:60, height:60, title:'ae86'},
    { src:"http://i.imgur.com/bjnH4nN.gif", width:106, height:66, title:'ritsu'},
    { src:"http://smashboards.com/attachments/salty-duane-gif.34388/", width:60, height:74, title:'saltyduane'},
    { src:"http://s9.postimg.org/7jgdsbfe3/Joey_transparent.png", width:60, height:60, title:'joey'},
    { src:"https://i.areyoucereal.com/HGbLpu.gif", width:33, height:50, title:'snoop2'},
    { src:"http://i.imgur.com/AiqM7ep.gif", width:66, height:50, title:'kakyoin'},
    { src:"http://i.imgur.com/RDP8xDj.gif", width:49, height:70, title:'arthur'},
    { src:"http://i.imgur.com/A57Z837.gif", width:50, height:60, title:'clippy'},
    { src:"http://i.imgur.com/ojyywy4.gif", width:67, height:50, title:'kirino'},
    { src:"http://i.imgur.com/pKXZaQM.gif", width:67, height:50, title:'monkey'},
    { src:"http://i.imgur.com/FXmuLOs.gif", width:67, height:50, title:'bustin'},
    { src:"http://i.imgur.com/EOW60AQ.gif", width:60, height:60, title:'sonic2'},
    { src:"http://i.imgur.com/uTUjZpq.png", width:50, height:50, title:'feelsscared'},
    { src:"http://i.imgur.com/9gVht7Y.gif", width:60, height:60, title:'dj'},
    { src:"http://i.imgur.com/K5H6tns.png", width:54, height:55, title:'nonon'},
    { src:"http://i.imgur.com/cCkq4Yb.gif", width:55, height:38, title:'goblinu2'},
    { src:"http://i.imgur.com/0NFfYFq.gif", width:55, height:38, title:'^'},
    { src:"http://i.imgur.com/RpznRYJ.gif", width:40, height:45, title:'yee'},
    { src:"http://i.imgur.com/ZEE0jZF.gif", width:66, height:66, title:'diddy'},
    { src:"http://i.imgur.com/uDUO8Nw.gif", width:57, height:45, title:'freedum'},
    { src:"http://i.imgur.com/NiMJaW6.png", width:30, height:40, title:'kappa'},
    { src:"http://i.imgur.com/vETtK.png", width:17, height:24, title:'myminisides'},
    { src:"http://i.imgur.com/vETtK.png", width:17, height:24, title:'mytinysides'},
    { src:"http://i.imgur.com/4wunBBM.png", width:60, height:52, title:'slut'},
    { src:"http://i.imgur.com/Gx5wmqn.gif", width:67, height:50, title:'wow2'},
    { src:"http://i.imgur.com/RoQiAtP.png", width:43, height:52, title:'expanddong'},
    { src:"http://i.imgur.com/8WGVGYh.gif", width:35, height:59, title:'cyrax'},
    { src:"http://i.imgur.com/cbQdL4A.png", width:39, height:67, title:'lel5'},
    { src:"http://i.imgur.com/7AyGv1a.gif", width:60, height:74, title:'ayylmao'},
    { src:"http://i.imgur.com/fNkI3M5.gif", width:40, height:60, title:'gigalien'},
    { src:"http://i.imgur.com/RgnpAPE.gif", width:45, height:59, title:'ayylien'},
    { src:"http://i.imgur.com/jBji5uc.gif", width:43, height:63, title:'alien2'},
    { src:"http://i.imgur.com/nfDwcil.png", width:40, height:56, title:'gookfood'},
    { src:"http://i.imgur.com/1ZAz974.jpg", width:45, height:56, title:'jimmies'},
    { src:"http://i.imgur.com/BeaCBjD.png", width:37, height:39, title:'feek'},
    { src:"http://i.imgur.com/BeaCBjD.png", width:37, height:40, title:'feeksbadman'},
    { src:"http://i.imgur.com/4zsobUd.png", width:36, height:61, title:'disgusting'},
    { src:"http://i.imgur.com/TvtnuqI.gif", width:70, height:45, title:'yes'},
    { src:"http://i.imgur.com/QZ4qCEE.gif", width:68, height:60, title:'calcium'},
    { src:"http://i.imgur.com/LNkPkIn.png", width:52, height:52, title:'topkek'},
    { src:"http://i.imgur.com/5pDD0HW.gif", width:55, height:55, title:'snab'},
    { src:"http://i.imgur.com/DxlIunk.png", width:60, height:60, title:'sweat'},
    { src:"http://i.imgur.com/EWhvuNJ.png", width:57, height:55, title:'whores'},
    { src:"http://i.imgur.com/qzKaSUr.png", width:36, height:37, title:'333'},
    { src:"http://i.imgur.com/HDCgmfx.jpg", width:30, height:50, title:'ragu'},
    { src:"http://i.imgur.com/jhuvqTo.gif", width:60, height:56, title:'pull'},
    { src:"http://i.imgur.com/WMwbr7n.gif", width:60, height:56, title:'push2'},
    { src:"http://i.imgur.com/b3ex5cx.png", width:42, height:49, title:'riptheskin'},
    { src:"http://i.imgur.com/oDLeCCu.gif", width:65, height:60, title:'iamthesun'},
    { src:"http://i.imgur.com/GI19OKs.png", width:41, height:45, title:'sanic2'},
    { src:"http://i.imgur.com/GI19OKs.png", width:41, height:45, title:'snoic'},
    { src:"http://i.imgur.com/34vCnqr.gif", width:80, height:53, title:'neat'},
    { src:"http://i.imgur.com/Wwk7Ce2.jpg", width:41, height:45, title:'haruka'},
    { src:"http://i.imgur.com/wAVQL4D.gif", width:60, height:47, title:'wop'},
    { src:"http://i.imgur.com/kXXQOwq.png", width:40, height:56, title:'modabuse'},
    { src:"http://i.imgur.com/JIqXkac.png", width:50, height:50, title:'feelssuicidal'},
    { src:"http://i.imgur.com/zR8xP2G.png", width:39, height:39, title:'feelsmadman'},
    { src:"http://i.imgur.com/zR8xP2G.png", width:39, height:39, title:'feelsmad'},
    { src:"http://i.imgur.com/byEQnHn.png", width:62, height:70, title:'lewd'},
    { src:"http://i.imgur.com/5FtdsyK.gif", width:75, height:50, title:'lewd2'},
    { src:"http://i.imgur.com/SCpPihV.gif", width:60, height:60, title:'smuganime'},
    { src:"http://i.imgur.com/2OmBZZU.gif", width:60, height:60, title:'anime'},
    { src:"http://i.imgur.com/pJznstY.jpg", width:60, height:60, title:'birthday'},
    { src:"http://i.imgur.com/qhJ9UBE.gif", width:75, height:55, title:'blink'},
    { src:"http://i.imgur.com/i807n8q.gif", width:75, height:41, title:'gigashark'},
    { src:"http://i.imgur.com/Uv3e0UT.gif", width:90, height:80, title:'hibiki'},
    { src:"https://38.media.tumblr.com/961a8b7582140768d50617450b928fa5/tumblr_ngh20fkbak1tl6vgyo1_250.gif", width:60, height:67.5, title:'illya'},
    { src:"http://i.imgur.com/r8LzdsE.jpg", width:60, height:60, title:'lefunnymeme'},
    { src:"http://i.imgur.com/d6lNkQR.gif", width:68, height:55, title:'lewd3'},
    { src:"http://i.imgur.com/sccZ18t.gif", width:60, height:60, title:'nyah'},
    { src:"http://i.imgur.com/rcIWIzw.gif", width:60, height:60, title:'nyah2'},
    { src:"http://i.imgur.com/zZzW3S2.gif", width:70,height:68, title:'awoo'},
    { src:"http://i.imgur.com/U5NVxsR.gif", width:55, height:55, title:'moe2'},
    { src:"http://i.imgur.com/s7jY2UX.gif", width:60, height:60, title:'idk'},
    { src:"http://i.imgur.com/zs8NHsQ.gif", width:70, height:80, title:'raiden'},
    { src:"http://i.imgur.com/FPf04tV.gif", width:60, height:60, title:'rare'},
    { src:"http://i.imgur.com/mPYJxxt.gif", width:75, height:42, title:'shark'},
    { src:"http://i.imgur.com/iFvF8q0.gif", width:60, height:55, title:'spam'},
    { src:"http://i.imgur.com/cIOR35M.gif", width:65, height:55, title:'lean'},
    { src:"http://a.pomf.se/jmyepv.png", width:65, height:55, title:'pomf2'},
    { src:"http://i.imgur.com/wQl8ly7.png", width:60, height:60, title:'clap'},
    { src:"http://i.imgur.com/fP7bAxr.gif", width:60, height:55, title:'ballin'},
    { src:"http://i.imgur.com/Qa31lT3.gif", width:60, height:60, title:'kitty3'},
    { src:"http://i.imgur.com/px7Zn4z.gif", width:60, height:60, title:'melon'},
    { src:"http://i.imgur.com/AJv1S35.gif", width:60, height:60, title:'n64'},
    { src:"http://i.imgur.com/xMQ8Iea.gif", width:70, height:45, title:'pour'},
    { src:"http://i.imgur.com/hUvNXZS.gif", width:55, height:40, title:'rekt'},
    { src:"http://i.imgur.com/QWONFwf.gif", width:60, height:50, title:'pew'},
    { src:"http://i.imgur.com/6UEZ2ar.gif", width:62, height:70, title:'shy'},
    { src:"http://i.imgur.com/d5O7WQN.gif", width:70, height:55, title:'stylin'},
    { src:"http://i.imgur.com/6HbdRYv.gif", width:60, height:70, title:'mememe2'},
    { src:"http://i.imgur.com/j7xljnX.gif", width:57, height:57, title:'moe'},
    { src:"http://i.imgur.com/TC093Pp.gif", width:60, height:60, title:'oo'},
    { src:"http://i.imgur.com/C0hi1NC.gif", width:60, height:60, title:'spooked'},
    { src:"http://i.imgur.com/nANdISW.gif", width:60, height:86.4, title:'hi'},
    { src:"http://i.imgur.com/h6M9I84.gif", width:75, height:50, title:'ree2'},
    { src:"http://i.imgur.com/ACwjF2U.gif", width:60, height:55, title:'blink2'},
    { src:"http://i.imgur.com/n8pl8H9.gif", width:75, height:66, title:'wow3'},
    { src:"http://i.imgur.com/4h4On1o.gif", width:70, height:50, title:'blink3'},
    { src:"http://i.imgur.com/vRgXgKd.gif", width:60, height:60, title:'chen4'},
    { src:"http://i.imgur.com/4qf8zh3.gif", width:45, height:70, title:'wop2'},
    { src:"http://i.imgur.com/FH5Y7Ni.gif", width:75, height:35, title:'ps'},
    { src:"http://i.imgur.com/WlYMFRt.gif", width:60, height:60, title:'doit'},
    { src:"http://i.imgur.com/iVNBNIT.gif", width:80, height:48, title:'killme'},
    { src:"http://i.imgur.com/vETtK.png", width:58.5, height:85, title:'myfuckingsides'},
    { src:"http://i.imgur.com/NpUPZSn.gif", width:80, height:80, title:'cirno'},
    { src:"http://i.imgur.com/D2kvAo7.gif", width:88, height:65, title:'bye'},
    { src:"http://i.imgur.com/LXaCgmO.png", width:36, height:54, title:'john'},
    { src:"http://i.imgur.com/AxWLGC5.png", width:51, height:60, title:'coolbama'},
    { src:"http://i.imgur.com/mSBT97m.gif", width:60, height:50, title:'clap2'},
    { src:"http://i.imgur.com/pd3vXcV.gif", width:72, height:64, title:'spin'},
    { src:"http://i.imgur.com/9M40dsy.png", width:60, height:60, title:'kojima'},
    { src:"http://i.imgur.com/09TQ5oP.png", width:33, height:54, title:'notbad'},
    { src:"http://i.imgur.com/78w0OiM.gif", width:60, height:69, title:'awoo2'},
    { src:"http://i.imgur.com/r5T9ym7.gif", width:56, height:54, title:'ken'},
    { src:"http://i.imgur.com/ONTL0jO.gif", width:58, height:61, title:'skelejii'},
    { src:"http://i.imgur.com/Y5BwP7X.png", width:46, height:44, title:'porn'},
    { src:"http://i.imgur.com/tGenRHO.gif", width:64, height:36, title:'brushie'},
    { src:"http://i.imgur.com/BXaEdRs.gif", width:60, height:80, title:'4u'},
    { src:"http://i.imgur.com/80nVcmr.gif", width:84, height:63, title:'o2'},
    { src:"http://i.imgur.com/20tobXF.gif", width:50, height:36, title:'feelsgooddance'},
    { src:"http://i.imgur.com/20tobXF.gif", width:50, height:36, title:'feelsguddance'},
    { src:"http://i.imgur.com/de9cG0t.gif", width:54, height:40, title:'corey'},
    { src:"http://i.imgur.com/omaV2Sh.png", width:80, height:80, title:'suicide'},
    { src:"http://i.imgur.com/CEuHLUK.gif", width:40, height:40, title:'cia'},
    { src:"http://i.imgur.com/KY2BoER.gif", width:53, height:74, title:'freshest'},
    ];

// Typically str.replace only checks the first instance so we need to pass in a regex.
// escapeRegExp deals with any special characters to make sure the substitution still works correctly.
// See http://stackoverflow.com/questions/1144783/replacing-all-occurrences-of-a-string-in-javascript
function escapeRegExp(str) {
    return str.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, "\\$1");
}
function replaceAll(str, find, replace) {
  return str.replace(new RegExp(escapeRegExp(find), 'g'), replace);
}

function registerChatListener() {
  API.on(API.CHAT, function(event) {
    var lastmsg = $(".text.cid-" + event.cid).get(0);
    for (var i=0; i<emotes.length; i++) {    
      newhtml = '<img src="' + emotes[i].src + '" height=' + emotes[i].height + ' width=' + emotes[i].width + '>';
      lastmsg.innerHTML = replaceAll(lastmsg.innerHTML, ':'+emotes[i].title+':', newhtml);
    }
  });
}
  
if (window.document.readyState === 'complete') {
  registerChatListener();
} else {
  window.addEventListener('load', registerChatListener, false);