// ==UserScript==
// @name         Anuncios habbos pirata
// @icon         https://i.imgur.com/0ncgMfu.png
// @namespace    Rodrigão
// @version      4.4.3
// @description  Amenizar todas propagandas
// @author       RodrigoLamek
// @match        https://www.ihabi.com.br/*
// @match        https://habblive.in/*
// @match        https://hebbuz.us/*
// @match        https://www.habby.in/*
// @match        https://www.jogarhabbo.us/*
// @match        https://agehotel.info/*
// @grant        none
// ==/UserScript==
$('#flash-container').mouseout(function() {
document.querySelector("body[id='client']").style = "background:url(https://i.imgur.com/usvSI7L.gif)";
$('center').remove();
$('#advn-ins').remove();
document.title = 'Anuncios Retirados';
document.querySelector("link[rel='shortcut icon']").href = "https://i.imgur.com/zPKT0g4.png";
$('#atlanta-stuff').remove();
$('#advn-ins').remove();
$('#advn-maincontainer').remove();
$('#advn-view0-container').remove();
$('#advn-click-container').remove();
$('#advn-click-content').remove();
$('ins').remove();
$('#alert').remove();
$('ins').remove();
$('style').remove();
$('iframe').remove();
$('#refresh').remove();
$('#k').remove();
$('#XcVCCW').remove();
$('script').remove();
$('link[href="//sb.advnetwork.net/auth.css?3"]').remove();
$('div[style="position:fixed; top:0; left:0; overflow:hidden;"]').remove();
$('script[src="https://www.youtube.com/iframe_api"]').remove();
$('script[src="http://habblive.in/static/js/neswAlerts.min.js"]').remove();
$('script[src="http://habblive.in/static/js/poll.min.n.js"]').remove();
$('link[href="http://tpc.googlesyndication.com/safeframe/1-0-29/html/container.html"]').remove();
$('link[href="https://adservice.google.com/adsid/integrator.js?domain=habblive.in"]').remove();
$('link[href="https://adservice.google.com.br/adsid/integrator.js?domain=habblive.in"]').remove();
$('script[src="https://adservice.google.com.br/adsid/integrator.js?domain=habblive.in"]').remove();
$('script[src="https://adservice.google.com/adsid/integrator.js?domain=habblive.in"]').remove();
$('script[src="https://securepubads.g.doubleclick.net/gpt/pubads_impl_249.js"]').remove();
$('script[src="https://www.googletagservices.com/tag/js/gpt.js"]').remove();
$('script[src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"]').remove();
$('script[src="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"]').remove();
$('script[src="//ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"]').remove();
$('script[src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js?0.07796396986265886"]').remove();
$('script[src="//advnetworkperformance.com/pagead/js/on__on_.js?_=0.13585861889429807"]').remove();
$('script[src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js?0.7619938332457039"]').remove();
$('script[src="https://s.ytimg.com/yts/jsbin/www-widgetapi-vflIAAJll/www-widgetapi.js"]').remove();
$('meta').remove();
$('.ads').remove();
$('.boton-p-c').remove();
$('.roomenterad-habblet-container').remove();
$('.white_content').remove();
$('.black_overlay').remove();
$('.roomenterad-Leet-container').remove();
$('.client_ads').remove();
$('.ads2').remove();
$('.room').remove();
$('.principal').remove();
$('.adsbygoogle').remove();
$('background-color').remove();
$('.audio').remove();
$('audio').remove();
$('.onmack').remove();
$('.player').remove();
$('.area-player').remove();
$('.player-min').remove();
$('.controles').remove();
$('.play-pause-box-min').remove();
$('.play-pause-box').remove();
$('.play-pause-min').remove();
$('.play-pause').remove();
$('.move-box').remove();
$('.pmove-min').remove();
$('.expand').remove();
$('.atlanta-ads-container-id-0').remove();
$('.atlanta-ads').remove();
$('.player_min').remove();
$('.roomenterad-habblet-container1').remove();
$('.player_min').remove();
$("div").remove(".google_center_div");
$("body").remove(".jar");
$("column3").remove(".jar");
$('#google_esf').remove();
$('#google_ads_frame1').remove();
$("#1_ad").remove();
$('.l_ad_backdrop').attr('style','display:none');
$('.mini').attr('style','display:none');
$(".mini").css("display","none");
$("div#anun_1").remove();
$("div#anun_2").remove();
$(".l_ad_backdrop").remove();
document.getElementById("programacao").innerHTML = '<span>SOUND SMILE</span>';
document.getElementById("locutor").innerHTML = '<span>DJ SMILE</span>';
document.getElementById("atlanta-ads").remove();
document.getElementById("atlanta-ads-container-id-0").remove();
document.getElementById("player").remove();
document.getElementById("area-player").remove();
var no = document.getElementById("l_ad");
if (no.parentNode) {
no.parentNode.removeChild(no);
}});
(function() {
$('center').remove();
$('#advn-ins').remove();
document.title = 'Anuncios Retirados';
document.querySelector("link[rel='shortcut icon']").href = "https://i.imgur.com/zPKT0g4.png";
$('#atlanta-stuff').remove();
$('#advn-ins').remove();
$('#advn-maincontainer').remove();
$('#advn-view0-container').remove();
$('#advn-click-container').remove();
$('#advn-click-content').remove();
$('ins').remove();
$('#alert').remove();
$('ins').remove();
$('style').remove();
$('iframe').remove();
$('#refresh').remove();
$('#k').remove();
$('#XcVCCW').remove();
$('script').remove();
$('link[href="//sb.advnetwork.net/auth.css?3"]').remove();
$('div[style="position:fixed; top:0; left:0; overflow:hidden;"]').remove();
$('script[src="https://www.youtube.com/iframe_api"]').remove();
$('script[src="http://habblive.in/static/js/neswAlerts.min.js"]').remove();
$('script[src="http://habblive.in/static/js/poll.min.n.js"]').remove();
$('link[href="http://tpc.googlesyndication.com/safeframe/1-0-29/html/container.html"]').remove();
$('link[href="https://adservice.google.com/adsid/integrator.js?domain=habblive.in"]').remove();
$('link[href="https://adservice.google.com.br/adsid/integrator.js?domain=habblive.in"]').remove();
$('script[src="https://adservice.google.com.br/adsid/integrator.js?domain=habblive.in"]').remove();
$('script[src="https://adservice.google.com/adsid/integrator.js?domain=habblive.in"]').remove();
$('script[src="https://securepubads.g.doubleclick.net/gpt/pubads_impl_249.js"]').remove();
$('script[src="https://www.googletagservices.com/tag/js/gpt.js"]').remove();
$('script[src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"]').remove();
$('script[src="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"]').remove();
$('script[src="//ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"]').remove();
$('script[src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js?0.07796396986265886"]').remove();
$('script[src="//advnetworkperformance.com/pagead/js/on__on_.js?_=0.13585861889429807"]').remove();
$('script[src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js?0.7619938332457039"]').remove();
$('script[src="https://s.ytimg.com/yts/jsbin/www-widgetapi-vflIAAJll/www-widgetapi.js"]').remove();
$('meta').remove();
$('.ads').remove();
$('.boton-p-c').remove();
$('.roomenterad-habblet-container').remove();
$('.white_content').remove();
$('.black_overlay').remove();
$('.roomenterad-Leet-container').remove();
$('.client_ads').remove();
$('.ads2').remove();
$('.room').remove();
$('.principal').remove();
$('.adsbygoogle').remove();
$('background-color').remove();
$('.audio').remove();
$('audio').remove();
$('.onmack').remove();
$('.player').remove();
$('.area-player').remove();
$('.player-min').remove();
$('.controles').remove();
$('.play-pause-box-min').remove();
$('.play-pause-box').remove();
$('.play-pause-min').remove();
$('.play-pause').remove();
$('.move-box').remove();
$('.pmove-min').remove();
$('.expand').remove();
$('.atlanta-ads-container-id-0').remove();
$('.atlanta-ads').remove();
$('.player_min').remove();
$('.roomenterad-habblet-container1').remove();
$('.player_min').remove();
$("div").remove(".google_center_div");
$("body").remove(".jar");
$("column3").remove(".jar");
$('#google_esf').remove();
$('#google_ads_frame1').remove();
$("#1_ad").remove();
$('.l_ad_backdrop').attr('style','display:none');
$('.mini').attr('style','display:none');
$(".mini").css("display","none");
$("div#anun_1").remove();
$("div#anun_2").remove();
$(".l_ad_backdrop").remove();
document.getElementById("programacao").innerHTML = '<span>SOUND SMILE</span>';
document.getElementById("locutor").innerHTML = '<span>DJ SMILE</span>';
document.getElementById("atlanta-ads").remove();
document.getElementById("atlanta-ads-container-id-0").remove();
document.getElementById("player").remove();
document.getElementById("area-player").remove();
})();