// ==UserScript==
// @name          Crunchyroll - Minimal Dark
// @namespace     https://greasyfork.org/en/scripts/23800-crunchyroll-minimal-dark
// @description	  A script to replace the CSS for crunchyroll to make it's theme less eyecancer.
// @author        Sil3nt Pr0digy
// @run-at        document-start
// @version       0.05
// ==/UserScript==
(function() {var css = "";
if (false || (new RegExp("^https?://www.crunchyroll.com/(?!user).*$")).test(document.location.href))
	css += [
		"body.main-page { background: url(http://i.imgur.com/maHp9zh.png) !important; background-color: #2c2c2c !important; background-attachment: fixed !important; background-size: 100% !important;}",
		"header.site-header { background-color: #2c2c2c !important;}",
		"ul li a { color: #AAAAAA !important; border-color: #AAAAAA !important; }",
		"input.header-searchbox { color: #AAA !important; background-color: #2c2c2c !important; border-color: #AAA !important; }",
		"div.cf.template-container { color: #AAA !important; background-color: #2c2c2c !important; border-color: #AAA !important; }",
		"div.cf.old-template-body { color: #AAA !important; background-color: #2c2c2c !important; border-color: #AAA !important; }",
		"div.welcome-block.clearfix h1 a { color: #AAA !important; background-color: #2c2c2c !important; border-color: #AAA !important; }",
		"#source_browse { color: #AAA !important; background-color: #2c2c2c !important; border-color: #AAA !important; }",
		"a.portrait-element.block-link.titlefix { color: #AAA !important; background-color: #323232 !important; border-color: #AAA !important; }",
		"div.welcome-block h1 a { color: #AAA !important; }",
		"h2.welcome-forum-category a { color: #AAA; }",
		"span.welcome-pulse-title { color: #AAA; }",
		"span.welcome-pulse-date { color: #AAA; }",
		"div.queue-wrapper.cf { background-color: #444; }",
		"a.landscape-element.episode.block-link.cf.titlefix.left { color: #AAA !important; background-color: #444 !important; }",
		"li.large-margin-bottom h3 { color: #AAA; }",
		"div.medium-margin-bottom.container-shadow { background-color: #444 !important; color: #AAA !important; }",
		"a.left.selected { color: #AAA !important; background-color: #333 !important; }",
		"a.left { color: #AAA !important; background-color: #444 !important; }",
		"p.small-margin-bottom { color: #AAA !important; }",
		"div.sub-tabs-menu.cf { background-color: #444 !important; }",
		"div.clearfix { background-color: #444 !important; }",
		"a.load-more.button.default-button.large-button { color: #AAA !important; border-color: #AAA !important; background-color: #2c2c2c !important; background: none !important; text-shadow: none !important; }",
		"a.landscape-element.block-link.cf.titlefix { color: #AAA !important; background-color: #444 !important; }",
		"div.content-menu.cf { background-color: #444 !important; border-color: #444 !important; }",
		"a.right.text-link.strong { color: #AAA !important; }",
		"a.right.calendar-link { color: #AAA !important; }",
		"a.portrait-element.block-link.titlefix.episode { background-color: #444 !important; }",
		"a.button.small-button.button-padding.default-button.left {background-color: #2c2c2c !important; color: #AAA !important; border-color: #AAA !important; background: none !important; text-shadow: none !important; }",
		"div.showmedia-submenu.white-wrapper.cf.container-shadow.small-margin-bottom { background-color: #444 !important; }",
		"div.white-wrapper.container-shadow.large-margin-bottom { background-color: #444 !important; }",
		"span.collection-carousel-overlay-top.ellipsis { color: #AAA !important; }",
		"div.comments-header.boxtitle h2 { color: #AAA !important; }",
		"textarea.guestbook-form.text-input.small-margin-bottom { color: #AAA !important; background-color: #2C2C2C !important; border-color: #AAA !important; }",
		"input.button.default-button.medium-button.button-padding.right { color: #AAA !important; background-color: #2C2C2C !important; border-color: #AAA !important; background: none !important; text-shadow: none !important; }",
		"div.guestbook-sort-bar { background-color: #444 !important; color: #AAA !important; border-color: #AAA !important; }",
		"#sort-selector { color: #AAA !important; background-color: #2C2C2C !important; border-color: #AAA !important; !important}",
		"div.guestbook-name a { color: #AAA !important; }",
		"a.comment-reply { color: #AAA !important; }",
		"input.more_comments.button.default-button.large-button { color: #AAA !important; background-color: #2C2C2C !important; border-color: #AAA !important; background: none !important; text-shadow: none !important; }",
		"div.large-margin-bottom h3 { color: #AAA !important; }",
		"a.text-link { color: #AAA !important; }",
		"p.availability-notes-low { color: #AAA !important; background-color: #444 !important; }",
		"div.medium-margin-bottom h4 { color: #AAA !important; }",
		"h4.strong { color: #AAA !important; }",
		"span.showmedia-subtitle-text a { color: #AAA !important; }",
		"div span a { color: #AAA !important; }",
		"#showmedia_about_info_details div span { color: #AAA !important; }",
		"a.button.default-button.medium-button.button-padding.left.xsmall-margin-right { color: #AAA !important; border-color: #AAA !important; background: none !important; text-shadow: none !important; background-color: #2c2c2c !important; }",
		"a.button.dark-button.medium-button.button-padding.left.xsmall-margin-right.selected { border-color: #AAA !important; background-color: #444 !important; }",
		"h1.ellipsis { color: #666 !important; }",
		"div.guestbook-body { color: #AAA !important; }",
		"div.message-item.clearfix.message-type-warning { color: #AAA !important; background-color: #2C2C2C !important; border-color: #AAA !important; }",
		"div.message-container.cf {background: none; border-color: #AAA !important; }",
		"div.message-item.clearfix.message-type-warning.message-item a { color: #AAA !important; }",
		"a.season-dropdown.content-menu.block.text-link.strong.open.small-margin-bottom { background-color: #444 !important; border-color: #AAA !important; }",
		"a.season-dropdown.content-menu.block.text-link.strong.small-margin-bottom { background-color: #444 !important; border-color: #AAA !important; }",
		"p.strong { color: #AAA !important; }",
		"span.trunc-desc { color: #AAA !important; }",
		"span.more { color: #AAA !important; }", 
		"div.other-series.large-margin-top h3 { color: #AAA !important; }",
		"div.strong.left.small-margin-right { color: #AAA !important; }",
		"li.white-wrapper.container-shadow.medium-margin-bottom { color: #AAA !important; background-color: #444 !important; }",
		"#showview_content_reviews h3 { color: #AAA !important; }",
		"span.left { color: #AAA !important; }",
		"a.right.button.button-padding.default-button.small-button { color: #AAA !important; border-color: #AAA !important; background: none !important; text-shadow: none !important; background-color: #2C2C2C !important; }",
		"a.paginator-lite-disabled { color: #AAA !important; background-color: #2C2C2C !important; border-color: #AAA !important; }",
		"span.paginator-lite-selected { color: #AAA !important; background-color: #2C2C2C !important; border-color: #AAA !important; }",
		"a.paginator-lite { color: #AAA; background-color: #2C2C2C !important; border-color: #AAA !important; }",
		"div.bb-quote.clearfix { color: #AAA; background-color: #2C2C2C !important; border-color: #AAA !important; }",
		"#showview_content_comments h3 { color: #AAA !important; }",
		"#showview_content_more h3 { color: #AAA !important; }",
		"#showview_content_shop h3 { color: #AAA !important; }", 
		"a.image { background-color: #2C2C2C !important; }",
		"a.name { color: #AAA !important; }",
		"li.cf.container-shadow { background-color: #444 !important; color: #AAA !important; }",
		"a.name { color: #AAA !important; }",
		"li.cf.container-shadow { background-color: #444 !important; color: #AAA !important; }",
		"div.news-left { color: #AAA !important; background-color: #2C2C2C !important; border-color: #AAA !important; }",
		"span.top-headline { color: #AAA !important; }",
		"div.cf.old-template-body { background-color: #2C2C2C !important; }",
		"li.highlight a { color: #AAA !important; background-color: #444 !important; border-color: #AAA !important; }",
		"li.dim a { color: #AAA !important; background-color: #444 !important; }",
		"div.byline { color: #AAA !important; }",
		"li.news-date-label { color: #AAA !important; }",
		"li.news-item h2 a { color: #AAA !important; }",
		"li.news-item h3 a { color: #AAA !important; }", 
		"h1.news-header-right.cr-header a { color: #AAA !important; }",
		"div.forum_main-topic-desc { background-color: #444 !important; border-color: #AAA !important; color: #AAA !important; background: none !important; }",
		"a.forum_main-topic-desc-title { color: #AAA !important; }",
		"a.group-card { background: none !important; background-color: #444 !important; }",
		"span.group-card-name { color: #AAA !important; }",
		"span.group-card-headline { color: #AAA !important; }",
		"ul.group-card-details li { color: #AAA !important; }",
		"div.topbar-nav-trail.clearfix a { color: #AAA !important; }",
		"div.widget-forumcategory-display-nomod a { color: #AAA !important; }",
		"form.search-form-channel input { background-color: #2C2C2C !important; color: #AAA !important; border-color: #AAA !important; }",
		"a.widget-forumcategory-header-title { color: #AAA !important; }",
		"td.forum_series-display-title a { color: #AAA !important; }",
		"a.widget-forumnav-structure-item.widget-forumnav-root span { color: #AAA !important; }",
		"a.widget-forumnav-children.container-shadow.hover-bubble.clearfix span { color: #AAA !important; }",
		"div.message-container { background: none !important; background-color: #2C2C2C !important; border-color: #AAA !important; }",
		"input.search-field { color: #AAA !important; background-color: #2C2C2C !important; border-color: #AAA !important; }",
		"textarea.reply-form.small-margin-bottom { color: #AAA !important; background-color: #2C2C2C !important; border-color: #AAA !important; }",
		"p.medium-margin-bottom { color: #AAA !important; }",
		"div.more-options { background-color: #333 !important; }",
		"p.description { color: #AAA !important; }",
		"li.large-margin-bottom ul li { color: #AAA !important; }",
		"div.description.markdown p { color: #AAA !important; }",
		"div.daily-deal.container-shadow { background-color: #444 !important; }",
		"a.title h3 { color: #AAA !important; }",
		"div.padding { color: #AAA; background-color: #444 !important; }",
		"td.promotion.container-shadow { background-color: #444 !important; }",
		"input.text-input.email-subscribe-margin { color: #AAA !important; background-color: #2C2C2C !important; border-color: #AAA !important; }",
		"#store_product_name { color: #AAA !important; }",
		"div.buy-actions.white-wrapper.container-shadow { background-color: #444 !important; }",
		"div.buy-actions.white-wrapper.container-shadow div label { color: #AAA !important; }",
		"#quantity-select { background-color: #2C2C2C; color: #AAA !important; border-color: #AAA !important; }",
		"#store_product_description_outer div h2 { color: #AAA !important; }",
		"div.medium-margin-top.markdown p { color: #AAA !important; }",
		"tbody tr td { color: #AAA !important; }",
		"li.store-bar-category a { background-color: #444 !important; color: #AAA !important; }",
		"ul.store-categories { background-color: #444 !important; }",
		"a.store-menu-item.sub-sub-category { color: #AAA !important; }",
		"ul li label { color: #AAA !important; }",
		"h3.accordion-title.no-selected.ui-accordion-header.ui-helper-reset.ui-corner-top.ui-accordion-header-active.ui-state-active.ui-state-default.ui-corner-bottom { background-color: #444 !important; }",
		"span.title { color: #AAA !important; }",
		"a.store-menu-item.sub-category { color: #AAA !important; background-color: #444 !important; }",
		"span.selectboxit-text { color: #AAA !important; }",
		"span.selectboxit.select-styled.selectboxit-enabled.selectboxit-btn.selectboxit-focus { background-color: #444 !important; }",
		"span.selectboxit.select-styled.selectboxit-enabled.selectboxit-btn.selectboxit { background-color: #444 !important; }",
		"h3.filter-label { background-color: #444 !important; }",
		"div.accordion-body.ui-accordion-content.ui-helper-reset.ui-widget-content.ui-corner-bottom ul li { background-color: #444 !important; }",
		"li.filter-see-more a { color: #AAA !important; }",
		"h3.accordion-title { color: #AAA !important; background-color: #444 !important; }",
		"h2.store-sub-menu-header.deals-label.back { color: #AAA !important; background-color: #444 !important; }",
		"h2.store-sub-menu-header.deals-label { color: #AAA !important; background-color: #444 !important; }",
		"div.category-dropdown ul li { border-color: #444 !important; }",
		"div.category-dropdown { border-color: #444 !important; }",
		"div.paginator-page { color: #AAA !important; }",
		"a.button.default-button.medium-button.paginator-category-page-button.button-padding.disabled { color: #AAA; background-color: #2C2C2C; border-color: #AAA; text-shadow: none; }",
		"a.button.default-button.medium-button.paginator-category-page-button.button-padding { color: #AAA; background-color: #2C2C2C; border-color: #AAA; background: none; text-shadow: none; }",
		"#store_number_navSelectBoxItOptions { color: #AAA !important; background-color: #444 !important; }",
		"li.item-subsubcategory a:hover { color: #AAA !important; background-color: #666 !important; }",
		"li.sel a { background-color: #333 !important; }",
		"span.tag { color: #AAA !important; background-color: #444 !important; }",
		"span.tag strong { color: #AAA !important; }",
		"#page_back { color: #AAA !important; background-color: #2C2C2C !important; border-color: #AAA; }", 
		"#page_next { color: #AAA !important; background-color: #2C2C2C !important; border-color: #AAA; }"
		
	].join("\n");
css += "color: #F88225 !import";
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node); 
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();