// ==UserScript==
// @name         WARCLICKS Extreme Mod!
// @namespace    WARCLICKS Extreme Mod!
// @version      5
// @description  Free Backgrounds, Custom Backgrounds and More!
// @author       TigerYT
// @match        *://warclicks.com/*
// @require      https://code.jquery.com/jquery-3.3.1.slim.min.js
// ==/UserScript==

window.location.replace("#header-text");
$('.header-text').attr('id', 'header-text');
$('img[src="https://s3-eu-west-1.amazonaws.com/warclicks-bucket/public_html/assets/images/new/warClicks/homepage/logo_new.png"').attr('src', 'https://cdn.discordapp.com/attachments/440904285019045898/481383026526388234/logo_new.png');
$('#menuOverlay > div.right > div.menus > div.burger-menu.hidden').after('<div class="button mod" data-title="Game menu" data-title-position-right="right" cursortype="pointer"></div>');
$('#settings').after('<div id="mod" class="window hidden" style="display: block;"><div class="mod_window"> <div class="outer-background"> <div class="background"> <div class="left"> </div><div class="right"> </div> </div> <div class="head"> <div class="left"> <div class="settings_icon"></div>MODDED MENU</div><div class="right"> <div class="button close" cursortype="pointer"></div> </div> </div> <div class="content"> <div class="title"> <!--<div class="save"> <span></span> <div class="save_icon"></div> <div class="save_text"> GAME PROGRESS LAST SAVED <b><span>35</span> SECONDS AGO</b> </div> <div class="button save disabled">SAVE NOW</div> </div>--> <div class="left"> BOOT CAMP </div><div class="right"> WAR ZONE </div> </div> <div class="setting sound"> <div class="title">Background</div> <div class="left"> <div class="sub_setting"> <div class="left">Background 1</div><div class="right" data-type="tc"> <div class="audio_icon music on" data-type="music" cursortype="pointer"></div> </div> </div> <div class="sub_setting"> <div class="left">Background 2</div><div class="right" data-type="tc"> <div class="audio_icon sound on" data-type="sound" cursortype="pointer"></div> </div> </div> <div class="sub_setting"> <div class="left">Background 3</div><div class="right" data-type="tc"> <div class="audio_icon sound on" data-type="sound" cursortype="pointer"></div> </div> </div></div><div class="right"> <div class="sub_setting"> <div class="left">Background 1</div><div class="right" data-type="wz"> <div class="audio_icon music on" data-type="music" cursortype="pointer"></div> </div> </div> <div class="sub_setting"> <div class="left">Background 2</div><div class="right" data-type="wz"> <div class="audio_icon sound on" data-type="sound" cursortype="pointer"></div> </div> </div> <div class="sub_setting"> <div class="left">Background 3</div><div class="right" data-type="wz"> <div class="audio_icon music on" data-type="quality4" cursortype="pointer"></div> </div> </div> </div> </div> <!-- <div class="setting numbers"> <div class="title">NUMBER DISPLAY</div> <div class="left"> <div class="sub_setting"> <div class="left"> SCIENTIFIC NOTATION </div><div class="right" data-type="tc"> <div class="checkbox radio off" data-type="numbersSpecial"></div> </div> </div> <div class="sub_setting"> <div class="left"> SPECIAL SIGNS </div><div class="right" data-type="tc"> <div class="checkbox radio on" data-type="numbersSpecial"></div> </div> </div> </div><div class="right"> <div class="sub_setting"> <div class="left"> SCIENTIFIC NOTATION </div><div class="right" data-type="wz"> <div class="checkbox radio off" data-type="numbersSpecial"></div> </div> </div> <div class="sub_setting"> <div class="left"> SPECIAL SIGNS </div><div class="right" data-type="wz"> <div class="checkbox radio on" data-type="numbersSpecial"></div> </div> </div> </div> </div> --> <div class="setting animation"> <div class="title">ANIMATION QUALITY</div> <div class="left"> <div class="sub_setting"> <div class="left"> PP gain </div><div class="right" data-type="tc"> <div class="checkbox on" data-type="quality0" cursortype="pointer"></div> </div> </div> <!-- <div class="sub_setting"> <div class="left"> PP spend </div><div class="right" data-type="tc"> <div class="checkbox on" data-type="quality1"></div> </div> </div> <div class="sub_setting"> <div class="left"> Unit cycling </div><div class="right" data-type="tc"> <div class="checkbox on" data-type="quality2"></div> </div> </div> <div class="sub_setting"> <div class="left"> Constant cycling </div><div class="right" data-type="tc"> <div class="checkbox on" data-type="quality3"></div> </div> </div> --> <!-- <div class="sub_setting"> <div class="left"> QUALITY #5 </div><div class="right" data-type="tc"> <div class="checkbox on" data-type="quality4"></div> </div> </div> --> </div><div class="right"> <div class="sub_setting"> <div class="left"> Particles </div><div class="right" data-type="wz"> <div class="checkbox on" data-type="quality0" cursortype="pointer"></div> </div> </div> <div class="sub_setting"> <div class="left"> Unit explosion </div><div class="right" data-type="wz"> <div class="checkbox on" data-type="quality1" cursortype="pointer"></div> </div> </div> <div class="sub_setting"> <div class="left"> Unit shaking </div><div class="right" data-type="wz"> <div class="checkbox on" data-type="quality2" cursortype="pointer"></div> </div> </div> <div class="sub_setting"> <div class="left"> Autoclicker enabled </div><div class="right" data-type="wz"> <div class="checkbox on" data-type="quality3" cursortype="pointer"></div> </div> </div> <!-- <div class="sub_setting"> <div class="left"> QUALITY #4 </div><div class="right" data-type="wz"> <div class="checkbox on" data-type="quality3"></div> </div> </div> <div class="sub_setting"> <div class="left"> QUALITY #5 </div><div class="right" data-type="wz"> <div class="checkbox on" data-type="quality4"></div> </div> </div> --> </div> </div> <div class="divider"> <div class="left"> </div><div class="right"> </div> </div> <div class="other"> <div class="title">OTHER</div> <div class="left"> <div class="sub_setting"> <div class="left"> Gain per second </div><div class="right" data-type="tc"> <div class="checkbox radio on" data-type="gainPerCycle" cursortype="pointer"></div> </div> </div> <div class="sub_setting"> <div class="left"> Gain per cycle </div><div class="right" data-type="tc"> <div class="checkbox radio off" data-type="gainPerCycle" cursortype="pointer"></div> </div> </div> <div class="sub_setting"> <div class="left"> Show tutorial </div><div class="right" data-type="tc"> <div class="checkbox on" data-type="quality4" cursortype="pointer"></div> </div> </div> <div class="sub_setting"> <div class="left"> Receive War Clicks Updates via email </div><div class="right" data-type="generalSetting"> <div class="checkbox off" data-type="emailSetting" cursortype="pointer"></div> </div> </div> <div class="sub_setting"> <div class="left"> Enable chat </div><div class="right" data-type="generalSetting"> <div class="checkbox on" data-type="chatEnabled" cursortype="pointer"></div> </div> </div> <div class="sub_setting"> <div class="left"> Daily reset notice visible </div><div class="right" data-type="generalSetting"> <div class="checkbox on" data-type="dailyResetNoticeVisible" cursortype="pointer"></div> </div> </div> </div> <div class="right"> <div class="save"> <span></span> <div class="save-text"> Progress last saved <b><span>0</span> seconds ago</b> </div> <div class="button progress <!--disabled-->" data-title="You can save your progress every 30 seconds manually" cursortype="pointer">SAVE PROGRESS</div> <div class="save-icon"></div> <div class="button restore <!--disabled-->" cursortype="pointer">RESTORE</div> <div class="button save_settings <!--disabled-->" cursortype="pointer">SAVE SETTINGS</div> </div> </div> </div> </div> </div></div></div>');
$('.mod').on('click', function() { $('#mod').css('display', 'block'); } );

(function() {var css = [
"#menuOverlay > div.right > div.menus > div.button.mod {",
"  background: url(https://upload.wikimedia.org/wikipedia/en/9/99/Mod_Pizza_logo.png);",
"  background-size: 100% 100%;",
"  margin-left: 4px;",
"  margin-top: 10px;",
"}",
"",
"#dailyReset {",
"  margin-left: -10px;",
"}",
"",
"#gameHelp {",
"  margin-right: -16px;",
"}",
"",
"#header_logo img {",
"    margin-left: 7.5%;",
"}"
"",
"#menuOverlay > div.right > div.menus > div.button.mod {",
"  background: url(https://upload.wikimedia.org/wikipedia/en/9/99/Mod_Pizza_logo.png);",
"  background-size: 100% 100%;",
"  margin-left: 4px;",
"  margin-top: 10px;",
"}",
"",
"#dailyReset {",
"  margin-left: -10px;",
"}",
"",
"#gameHelp {",
"  margin-right: -16px;",
"}",
"",
"#header_logo img {",
"    margin-left: 7.5%;",
"}",
"",
"#mod {",
"    position: absolute;",
"    z-index: 1501;",
"",
"    top: 0;",
"",
"    width: 100%;",
"}",
"#mod >.mod_window {",
"    position: relative;",
"",
"    margin: 0 auto;",
"",
"    width: 685px;",
"/*    height: 500px;*/",
"",
"    padding-bottom: 10px;",
"",
"    background: #ecf0f1;",
"",
"    box-shadow: 0 3px 4px black;",
"    /*background: white;*/",
"}",
"#mod >.mod_window .outer-background{",
"    position: relative;",
"    width: 643px;",
"    height: 507px;",
"    height: 529px;",
"    background: #ecf0f1;",
"    margin-left: 21px;",
"}",
"#mod .mod_window .background {",
"    position: absolute;",
"",
"    left: 0;",
"    top: 0;",
"",
"    width: 100%;",
"    height: 100%;",
"}",
"#mod .mod_window .background >div {",
"    position: relative;",
"    display: inline-block;",
"",
"    width: 50%;",
"    /*height: 447px;*/",
"    /*height: 470px;*/",
"    height: 492px;",
"    height: 518px;",
"}",
"#mod .mod_window .background >.left {",
"    background: #cfd6d7",
"    /*background: #c2b49b;*/",
"}",
"#mod .mod_window .background >.right {",
"    /*background: #96876b;*/",
"    background: #999999;",
"}",
"#mod .head {",
"    position: relative;",
"",
"    width: 100%;",
"    height: 66px;",
"",
"    font: 36px/40px 'titilliumWebRegular';",
"    color: black;",
"    background: #ecf0f1;",
"}",
"#mod .content {",
"    position: relative;",
"",
"    width: 100%;",
"    height: calc(100% - 55px);",
"}",
"",
"",
"",
"#mod .head >div {",
"    position: relative;",
"    display: inline-block;",
"",
"    width: calc(50% - 4px);",
"    height: calc(100% - 2 * 7px);",
"",
"    vertical-align: top;",
"}",
"#mod .head >.left {",
"    color: #f7931e;",
"    margin: 16px 0 7px 4px;",
"",
"    font: 21px/34px 'titilliumWebSemiBold';",
"    border-radius: 8px 0 0 8px;",
"",
"    /*background: #96876b;*/",
"}",
"#mod .head >.right {",
"    margin: 7px 4px 7px 0;",
"",
"    border-radius: 0 8px 8px 0;",
"",
"}",
"#mod .head >.left >div {",
"    vertical-align: top;",
"}",
"#mod .head .mod_icon {",
"    top: 2px;",
"    position: relative;",
"    display: inline-block;",
"",
"    /*width: 42px;",
"    height: 35px;*/",
"    width: 40px;",
"    height: 30px;",
"",
"    background: url("../images/new/warClicks/sp_1_min.png") -200px 0;",
"",
"    transform: scale(0.8);",
"}",
"#mod .head .right .button {",
"    position: absolute;",
"",
"    top: 0;",
"    right: -10px;",
"",
"    margin: 4px;",
"    width: 36px;",
"    height: 36px;",
"",
"    color: black;",
"",
"    background: url("../images/new/warClicks/wc_splosno/sp_2_close_min.png") 0 0",
"}",
"",
"#mod .head .right .button:hover {",
"    background-position-y: -36px;",
"    /*cursor: url("../images/cursorPointer.ico") 11 1, pointer;*/",
"}",
"#mod .content .left, #mod .content .right {",
"    position: relative;",
"    display: inline-block;",
"",
"    width: 50%;",
"    width: 319px;",
"",
"    vertical-align: top;",
"}",
"#mod .content .left .left, #mod .content .right .left {",
"    padding-left: 5%;",
"",
"    width: calc(65% - 5%);",
"",
"    text-align: left;",
"}",
"#mod .content .left .right, #mod .content .right .right {",
"    width: 35%;",
"",
"    text-align: center;",
"}",
"#mod .content > .title {",
"    position: relative;",
"",
"    width: 100%;",
"    height: 38px;",
"}",
"#mod .content .title >.left, #mod .content .title > .right {",
"    font: 16px/18px 'titilliumWebSemiBold';",
"    color: white;",
"    left: 44px;",
"    top: 10px;",
"    text-align: left;",
"}",
"",
"#mod .content .title > .left{",
"    color: black;",
"}",
"",
"",
"#mod .content > .setting {",
"    position: relative;",
"",
"    width: 100%;",
"",
"    /*padding-bottom: 4px;*/",
"}",
"/*#mod .content > .setting.animation {",
"    height: 107px;",
"}*/",
"#mod .content > .setting.sound .left, #mod .content > .setting.sound .right{",
"    margin-top: 3px;",
"}",
"#mod .content .setting > .title {",
"    position: relative;",
"    left: -7px;",
"    padding: 0 11px 0 50px;",
"    width: calc(100% - 2 * 24px);",
"    height: 24px;",
"",
"    font: 14px/24px 'titilliumWebSemiBold';",
"    color: white;",
"",
"    background: #f7931e;;",
"}",
"/*",
"#mod .content .setting.sound {",
"    height: 88px;",
"}",
"#mod .content .setting.numbers {",
"    height: 70px;",
"}",
"#mod .content .setting.animation {",
"    height: 126px;",
"}",
"*/",
"",
"/*#mod .content .setting >.left, */",
"#mod .content .setting >.right {",
"    height: calc(100% - 24px);",
"}",
"#mod .content .setting >.left{",
"    height: 110px;",
"}",
"#mod .content .setting >.right {",
"    color: white;",
"}",
"#mod .content .sub_setting {",
"    position: relative;",
"",
"    width: 100%;",
"    padding-top: 3px;",
"",
"    font: 12px/23px 'titilliumWebRegular';",
"    color: black;",
"}",
"#mod .content .sub_setting .left, #mod .content .setting .sub_setting .right {",
"    vertical-align: middle;",
"    font: 12px/21px 'titilliumWebRegular';",
"}",
"#mod .content .right .sub_setting .left {",
"    color: white;",
"}",
"#mod .content .sub_setting .checkbox {",
"    position: relative;",
"    display: inline-block;",
"",
"    width: 13px;",
"    height: 13px;",
"",
"    background: url("../images/checkbox_green.png") 0 0;",
"}",
"#mod .content .sub_setting .checkbox.on {",
"    background-position-x: -13px;",
"}",
"#mod .content .sub_setting .checkbox:hover:not(.radio) {",
"    /*cursor: url("../images/cursorPointer.ico") 11 1, pointer;*/",
"}",
"#mod .content .sub_setting .checkbox.radio:hover:not(.on) {",
"    /*cursor: url("../images/cursorPointer.ico") 11 1, pointer;*/",
"}",
"#mod .content .sub_setting .audio_icon {",
"    position: relative;",
"    display: inline-block;",
"",
"    width: 33px;",
"    height: 24px;",
"",
"    background: url("../images/new/warClicks/mod/music_buttons_sprite_min.png") 0 0;",
"}",
"#mod .content .sub_setting .audio_icon:hover {",
"    background-position-y: -24px;",
"    /*cursor: url("../images/cursorPointer.ico") 11 1, pointer;*/",
"}",
"#mod .content .sub_setting .audio_icon.off {",
"    background-position-x: -33px;",
"}",
"",
"#mod .content >.divider {",
"    position: relative;",
"",
"    width: 100%;",
"    height: 0px;",
"}",
"#mod .content >.divider >div {",
"    height: 100%;",
"}",
"#mod .content .divider >.left {",
"    /*background: #96876b;*/",
"}",
"#mod .content .divider >.right {",
"    /*background: #c2b49b;*/",
"}",
"",
"",
"",
"#mod .content >.other {",
"    position: relative;",
"",
"    width: 100%;",
"}",
"#mod .content >.other .left {",
"    margin-top: -3px;",
"    padding-top: 3px;",
"}",
"#mod .content .other >.title {",
"    position: absolute;",
"",
"    padding: 0 8px 0 49px;",
"",
"    width: calc(50% - 2 * 26px);",
"    height: 24px;",
"",
"    font: 14px/24px 'titilliumWebSemiBold';",
"    color: white;",
"    background: #333333;",
"    left: -5px;",
"    margin-top: -28px;",
"}",
"#mod .content .other >.right {",
"    margin-top: -24px;",
"    width: 30%;",
"}",
"#mod .content >.other .sub_setting {",
"    padding-top: 0px;",
"}",
"#mod .content .other .save .save-icon{",
"    position: absolute;",
"    width: 40px;",
"    height: 40px;",
"    left: 147px;",
"    top: 7px;",
"    background: url("../images/new/warClicks/mod/save_sprite_min.png");",
"}",
"",
"#mod .content .other .save .save-text{",
"    display: inline-block;",
"    font: 12px/14px 'titilliumWebRegular';",
"    width: 130px;",
"    left: 18px;",
"    top: 12px;",
"    position: absolute;",
"    text-align: center;",
"}",
"#mod .content .other .save-progress .button {",
"    display: inline-block;",
"}",
"#mod .content .other .save{",
"    position: relative;",
"    margin-top: 47px;",
"    margin-top: 73px;",
"    margin-left: -1px;",
"    width: 319px;",
"    width: 320px;",
"    height: 86px;",
"    background: #ecf0f1;",
"    padding-top: 6px;",
"    border: solid 1px lightgrey;",
"    text-align: right;",
"",
"}",
"#mod .content .other .save .button {",
"    display: inline-block;",
"",
"    top: 0;",
"    right: 0;",
"",
"    /*margin: 6px 16px 6px 0;*/",
"    margin: 8px 5px 5px 9px;",
"    padding: 0 8px;",
"",
"    border-radius: 8px;",
"",
"    font: 14px/27px 'titilliumWebBold';",
"",
"    color:white;",
"    background: #4bada4;",
"    width: 124px;",
"    text-align: center;",
"}",
"#mod .content .other .save .button.progress {",
"    margin-left:50px !important;",
"    padding-left: 13px;",
"}",
"#mod .content .other .save .button:hover {",
"    filter: brightness(130%);",
"    /*cursor: url("../images/cursorPointer.ico") 11 1, pointer;*/",
"}",
"#mod .content .other .save .button.disabled {",
"    margin: 8px 5px 5px 9px;",
"",
"    color: white;",
"",
"    background: none;",
"    background: #4bada4;",
"}",
"#mod .content .other .save .button:hover:not(.disabled) {",
"    color: white;",
"    /*cursor: url("../images/cursorPointer.ico") 11 1, pointer;*/",
"}"
].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();