// ==UserScript==
// @name          Deezer DarkCube
// @namespace     http://userstyles.org
// @description	  It's my <strong>dark</strong> reskin of the <strong>deezer.com</strong> website for users who like inverted colors that are easier on your eyes.
// @author        cubedj
// @homepage      https://userstyles.org/styles/142184
// @include       http://deezer.com/*
// @include       https://deezer.com/*
// @include       http://*.deezer.com/*
// @include       https://*.deezer.com/*
// @include       http://deezer.com/*
// @include       https://deezer.com/*
// @include       http://*.deezer.com/*
// @include       https://*.deezer.com/*
// @run-at        document-start
// @version       0.20190414134706
// ==/UserScript==
(function() {var css = "";
if (false || (document.domain == "deezer.com" || document.domain.substring(document.domain.indexOf(".deezer.com") + 1) == "deezer.com"))
	css += [
		"*::-webkit-scrollbar {",
		"	width: 13px !important;",
		"	height: 10px !important;",
		"	background: #111111 !important;",
		"	border: 1px solid #000 !important;",
		"}",
		"*::-webkit-scrollbar-thumb {",
		"	min-height: 28px !important;",
		"	background: #333333 !important;",
		"	border: 1px solid #555 !important;",
		"}",
		"::-webkit-scrollbar-track, ::-webkit-scrollbar-corner {",
		"	background: #111111 !important;",
		"	border: 1px solid #000 !important;",
		"}",
		"::-webkit-scrollbar-thumb:hover {",
		"	background: #0096ff !important;",
		"	border: 1px solid #000 !important;",
		"}",
		"",
		"body::-webkit-scrollbar-track-piece {",
		"	background-clip: padding-box;",
		"	background-color: #111;",
		"	border: solid #000;",
		"	border-width: 0 0 0 1px;",
		"	box-shadow: inset 1px 0 0 rgba(0,0,0,.14),inset -1px 0 0 rgba(0,0,0,.07)",
		"}",
		"::selection, ::-moz-selection, ::-webkit-selection {",
		"	color: #000 !important;",
		"	background-color: #0096ff !important;",
		"}",
		"a:active, a:visited {",
		"	color: #0096ff;",
		"}",
		"a:link {",
		"	color: #0096ff !important;",
		"}",
		"a:hover {",
		"	color: #FF6400 !important;",
		"}",
		"input {",
		"	color: #CCC;",
		"	font-weight: bold !important;",
		"}",
		"#livebar_menu a {",
		"	-moz-filter: invert(100%);",
		"	-webkit-filter: invert(100%);",
		"	filter: invert(100%);",
		"	border-color: #FF6400 !important;",
		"	border-left-color: #FF6400 !important;",
		"}",
		"#livebar_menu {",
		"	border-color: #0096ff !important;",
		"}",
		".channel-section {",
		"	background-color: #0a0a0a !important;",
		"}",
		"div.channel-section {",
		"	background-color: #191919 !important;",
		"}",
		".page-sidebar .player-controls > .controls.controls-options .volume-handler, .page-sidebar .player-progress .progress-handler {",
		"	background-color: #FF6400 !important;",
		"}",
		".page-sidebar .player-controls > .controls.controls-options .volume-progress-bar, .page-sidebar .player-progress .progress-buffer {",
		"	background-color: #969696 !important;",
		"}",
		".page-sidebar .player-controls > .controls.controls-options .volume-bar, .page-sidebar .player-progress .progress {",
		"	background-color: #0096ff !important;",
		"}",
		".page-sidebar .player-progress .progress-time, .page-sidebar .player-progress .progress-length {",
		"	color: #ffffff;",
		"	opacity: 1;",
		"}",
		".datagrid-table {",
		"	background: #0a0a0a;",
		"}",
		".datagrid-table tbody tr.active td {",
		"	background-color: rgba(255, 100, 0, .7);",
		"}",
		".datagrid-table tbody tr.active td.length {",
		"	color: #FFF;",
		"	font-weight: bold;",
		"}",
		".datagrid-table tbody tr.active:hover td.length {",
		"	color: #ff6400;",
		"	font-weight: bold;",
		"}",
		".datagrid-table tbody tr.active:hover td {",
		"	background-color: rgba(150, 150, 150, .5);",
		"}",
		".datagrid-table tbody tr.active a {",
		"	color: #FFF;",
		"	font-weight: bold;",
		"}",
		".datagrid-table tbody tr.active:hover a {",
		"	color: #ff6400;",
		"	font-weight: bold;",
		"}",
		".datagrid-table tbody tr:hover td {",
		"	background-color: rgba(150, 150, 150, .5);",
		"}",
		".datagrid-table tbody tr:hover td a {",
		"	color: #FFF;",
		"	font-weight: bold;",
		"}",
		".datagrid-table tbody tr:hover td.artist {",
		"	color: #FFF;",
		"	font-weight: bold;",
		"}",
		".datagrid-table tbody tr.song.active:hover td.artist {",
		"	color: #FFF;",
		"	font-weight: bold;",
		"}",
		".datagrid-table tbody tr.song.active td.artist {",
		"	color: #000;",
		"	font-weight: bold;",
		"}",
		".datagrid-table td, .datagrid-table th {",
		"	color: #AAA;",
		"}",
		".datagrid-table td.length {",
		"	color: #ff6400;",
		"}",
		".datagrid-table tbody tr.contributors td {",
		"	background-color: #191919;",
		"	color: #DDD;",
		"	font-weight: normal;",
		"}",
		".datagrid-table tbody tr.contributors:hover td {",
		"	background-color: rgba(150, 150, 150, .5);",
		"	color: #DDD;",
		"}",
		".datagrid-table tbody tr.caption:hover td {",
		"	background-color: rgba(150, 150, 150, 0.5);",
		"	color: #fff;",
		"}",
		".datagrid-table tbody tr.caption:hover td .icon-album {",
		"	color: #ff6400;",
		"}",
		".datagrid-table tbody tr.caption td .icon-album:hover {",
		"	color: #0096ff;",
		"}",
		".icon-datagrid {",
		"	color: #EEE;",
		"	transition-duration: .15s;",
		"	transition-property: color;",
		"}",
		".icon-datagrid:hover {",
		"	color: #ff6400;",
		"}",
		".loved .icon.active {",
		"	color: #ff0000 !important;",
		"}",
		".loved .icon:hover {",
		"	color: #ff0000 !important;",
		"}",
		".datagrid-table tbody tr td a {",
		"	color: #AAA;",
		"}",
		"a.link-gray {",
		"	color: #AAA;",
		"}",
		"input[type=checkbox] {",
		"	-webkit-filter: invert(100%) hue-rotate(180deg);",
		"	-moz-filter: invert(100%) hue-rotate(180deg);",
		"	filter: invert(100%) hue-rotate(180deg);",
		"}",
		"body:not(.paused):not([direction=\"ltr\"]) {",
		"	background-color: #0a0a0a !important;",
		"	color: #EEE !important;",
		"	font-family: \"Lucida Grande\", Arial, sans-serif;",
		"	font-size: 12px;",
		"	line-height: 1.33333333;",
		"	margin: 0;",
		"	/*padding: 0;*/",
		"}",
		".page-main, .catalog-header {",
		"	background-color: #0a0a0a !important;",
		"	color: #EEE;",
		"}",
		".navbar {",
		"	background-color: #0a0a0a;",
		"	color: #0096ff !important;",
		"	border-bottom: 1px solid #343434;",
		"}",
		".navbar {",
		"	-webkit-box-shadow: none;",
		"	box-shadow: none;",
		"}",
		".catalog-header .infos {",
		"	border-top: 1px solid #343434;",
		"}",
		"#page_profile .user-section {",
		"	border-bottom: 1px solid #343434;",
		"}",
		"#page_feed .info-down .heading-5.heading-bordered {",
		"	border-bottom: 1px solid #343434;",
		"}",
		"#page_feed .title_separ {",
		"	border-bottom: 1px solid #343434;",
		"}",
		"#page_feed .card-release-album .details ul > li + li {",
		"	border-top: 1px solid #343434;",
		"}",
		".heading-bordered {",
		"	border-bottom: 1px solid #343434;",
		"}",
		"#page_account .account-apps .app-cell {",
		"	border-bottom: 1px solid #343434;",
		"}",
		"div.catalog-content {",
		"	background-color: #0a0a0a;",
		"	color: #FFF;",
		"}",
		"#page_naboo_artist .content-left {",
		"	background-color: #0a0a0a;",
		"}",
		"#page_naboo_artist .content-left {",
		"	-webkit-box-shadow: none;",
		"	box-shadow: none;",
		"}",
		".naboo-catalog .catalog-tab-box, .page-naboo-search .search-header, .page-naboo-search .search-suggest {",
		"	background-color: #0a0a0a;",
		"}",
		".btn {",
		"	border: 1px solid transparent;",
		"	border-radius: 4px;",
		"	color: #FFF;",
		"	background-color: #0096ff;",
		"	cursor: pointer;",
		"	font-size: 12px;",
		"	margin: 0;",
		"	padding: 7px 12px;",
		"	vertical-align: middle;",
		"	transition-duration: .15s;",
		"	transition-property: background-color, border-color, color, opacity;",
		"}",
		".btn:hover {",
		"	background-color: #ff6400;",
		"	color: #000;",
		"}",
		".btn .label {",
		"	color: #FFF;",
		"}",
		".btn:hover .label {",
		"	color: #000;",
		"}",
		".line {",
		"	background-color: #343434 !important;",
		"}",
		"#page_naboo_artist .content-right {",
		"	border-bottom: 1px solid #343434;",
		"	border-top: 1px solid #343434;",
		"}",
		".btn > .action-active .icon-love {",
		"	color: #ff1e1e;",
		"}",
		".btn-group > .btn.btn-default.active {",
		"	background-color: #444444;",
		"	color: #0096FF;",
		"	border-color: #000;",
		"}",
		".btn-group > .btn.btn-default.active .label {",
		"	color: #ff6400;",
		"}",
		".btn-group > .btn.btn-default.active .icon {",
		"	color: #ff6400;",
		"}",
		".btn-group > .btn.btn-default.active:hover .icon {",
		"	color: #000;",
		"}",
		".btn-group > .btn.btn-default.active:hover .label {",
		"	color: #000;",
		"}",
		".btn-group > .btn.btn-default.active:hover {",
		"	background-color: #ff6400;",
		"	color: #000;",
		"	border-color: #ff6400;",
		"}",
		".page-sidebar {",
		"	background-color: #0f0f0f;",
		"	color: #EEE;",
		"}",
		".page-main, .page-scroll {",
		"	background-color: #0a0a0a;",
		"	color: #EEE;",
		"}",
		".page-sidebar .nav-link {",
		"	background-color: #0f0f0f;",
		"	color: #EEE;",
		"}",
		".page-sidebar .nav-link:hover {",
		"	background-color: #333;",
		"	color: #ff6400;",
		"}",
		".page-sidebar .nav-link:focus {",
		"	background-color: #1c1c1c;",
		"}",
		".page-sidebar .nav-link[href=\"/en/profile/1286179544/loved\"]:active {",
		"	background-color: #1c1c1c;",
		"	color: #ff6400;",
		"}",
		".page-sidebar .nav-link[href=\"/en/profile/1286179544/loved\"]:active .svg-icon {",
		"	fill: #0096ff;",
		"}",
		".page-sidebar .nav-link.active-link {",
		"	background-color: #1c1c1c;",
		"	border-left-color: #0096ff;",
		"	color: #eee;",
		"}",
		".page-sidebar .nav-link:hover .svg-icon {",
		"	fill: #0096ff;",
		"}",
		".page-sidebar .nav-link.active-panel {",
		"	background-color: #1c1c1c;",
		"	color: #ff6400;",
		"}",
		".page-sidebar .nav-link.active-panel .svg-icon {",
		"	fill: #0096ff;",
		"}",
		".page-sidebar .player-controls {",
		"	background-color: #0f0f0f;",
		"}",
		".page-sidebar .player-controls:hover {",
		"	background-color: #141414;",
		"}",
		".page-sidebar .player-controls > .controls > li > .control:hover {",
		"	color: #ff6400;",
		"}",
		".page-sidebar .search-control, .form-control ~ .page-panels, .catalog-tab-comment .post-comment .form-control, .datagrid-toolbar .toolbar-search .form-control, #page_profile .user-search .form-control {",
		"	-webkit-filter: invert(100%) hue-rotate(180deg);",
		"	-moz-filter: invert(100%) hue-rotate(180deg);",
		"	filter: invert(100%) hue-rotate(180deg);",
		"}",
		".page-sidebar .player-controls > .controls > li > .control.control-play:hover {",
		"	color: #ff6400;",
		"}",
		".heading-2 {",
		"	color: #EEE;",
		"}",
		".heading-1 a, .heading-1 a:hover, .heading-2 a, .heading-2 a:hover, .heading-3 a, .heading-3 a:hover, .heading-4 a, .heading-4 a:hover, .heading-5 a, .heading-5 a:hover {",
		"	color: #EEE;",
		"}",
		".page-panels .panel-container.opened .panel-wrapper .heading-4 a {",
		"	color: #0096ff;",
		"	text-shadow: 0 0 2px #fff;",
		"	-webkit-text-stroke: #0096ff .5px;",
		"}",
		".page-panels .panel-container.opened .panel-wrapper .heading-4 a:hover {",
		"	color: #ff6400;",
		"	text-shadow: 0 0 2px #fff;",
		"	-webkit-text-stroke: #ff6400 .5px;",
		"}",
		".page-panels .panel-container.opened .panel-wrapper .heading-4 a:visited {",
		"	color: #0096ff;",
		"	text-shadow: 0 0 2px #fff;",
		"	-webkit-text-stroke: #0096ff .5px;",
		"}",
		".page-panels .panel-container.opened .panel-wrapper .heading-4 a:visited:hover {",
		"	color: #ff6400;",
		"	text-shadow: 0 0 2px #fff;",
		"	-webkit-text-stroke: #ff6400 .5px;",
		"}",
		".page-panels .panel-wrapper {",
		"	-webkit-filter: invert(96%) hue-rotate(180deg);",
		"	-moz-filter: invert(96%) hue-rotate(180deg);",
		"	filter: invert(96%) hue-rotate(180deg);",
		"}",
		".page-panels .panel-heading-sub {",
		"	color: #000;",
		"	margin: 24px 0 8px;",
		"}",
		"#page_profile .user-section .user-section-suggestion {",
		"	background-color: #0f0f0f;",
		"}",
		".thumbnail .picture:after {",
		"	background-color: #EEE;",
		"	bottom: 0;",
		"	content: \"\";",
		"	left: 0;",
		"	opacity: 0;",
		"	position: absolute;",
		"	right: 0;",
		"	top: 0;",
		"	box-shadow: none;",
		"}",
		".thumbnail .picture.overlay-hidden {",
		"	background-color: #010101;",
		"}",
		".thumbnail:hover .picture.overlay-hidden {",
		"	background-color: #0096ff;",
		"}",
		".thumbnail {",
		"	box-shadow: none;",
		"}",
		".slide.slide-cut {",
		"	border: 1px solid #000;",
		"}",
		".btn-app .icon, .btn-default .icon, .btn-group > .btn-label .icon, .btn-slide .icon, .btn-telco .icon {",
		"	color: #000;",
		"}",
		".btn-app:hover .icon, .btn-default:hover .icon, .btn-group > .btn-label:hover .icon, .btn-slide:hover .icon, .btn-telco:hover .icon {",
		"	color: #FFF;",
		"}",
		".btn-group > .btn-label {",
		"	background-color: #444444;",
		"	border: 1px solid #0096ff;",
		"	color: #FFF;",
		"}",
		".btn-group > .btn-label:hover {",
		"	background-color: #ff6400;",
		"	color: #000;",
		"}",
		".datagrid-table thead th {",
		"	background-color: #2d2d2d;",
		"}",
		"#page_profile .user-listen {",
		"	background-color: #1a1a1a;",
		"	border-radius: 4px;",
		"	height: 40px;",
		"	box-shadow: 0 0 2px 1px rgba(0,150,255,.8);",
		"	border: 5px double rgba(0,0,0,.7);",
		"}",
		".heading-1-sub, .heading-2-sub, .heading-3-sub, .heading-4-sub, .heading-5-sub {",
		"	color: #EEE;",
		"}",
		".heading-4 {",
		"	color: #0096ff;",
		"}",
		".heading-4:hover {",
		"	color: #ff6400;",
		"}",
		".heading-1, .heading-2, .heading-3, .heading-5 {",
		"	color: #EEE;",
		"}",
		".create-assistant-container:hover {",
		"	background-color: #343434;",
		"}",
		".catalog-tab-comment .comment-message {",
		"	background-color: #222;",
		"}",
		".catalog-tab-comment .message-body {",
		"	color: #EEE;",
		"}",
		".navbar-nav > li.active > a {",
		"	color: #FFF;",
		"}",
		".dropdown .dropdown-menu ~ .page-panels, .popover {",
		"	-moz-filter: invert(100%) hue-rotate(180deg);",
		"	-webkit-filter: invert(100%) hue-rotate(180deg);",
		"	filter: invert(100%) hue-rotate(180deg);",
		"}",
		".page-contextmenu .menu-item:hover {",
		"	background-color: #ff6400;",
		"	color: #FFF;",
		"	-webkit-text-stroke: transparent 0px;",
		"}",
		".page-contextmenu .menu-item:hover .label {",
		"	color: #FFF;",
		"	-webkit-text-stroke: transparent 0px;",
		"}",
		".page-contextmenu .menu-item:hover .icon {",
		"	color: #000;",
		"	-webkit-text-stroke: transparent 0px;",
		"}",
		".page-contextmenu .menu-item.link {",
		"	background-color: transparent;",
		"	padding: 0 6px;",
		"}",
		".page-sidebar .nav-link.active-link, .page-sidebar .nav-link.active-panel {",
		"	background-color: #222;",
		"}",
		"textarea.form-control {",
		"	color: #000;",
		"}",
		".panel-qlist .panel-headings .heading-2, .page-panels .panel-headings .heading-2 {",
		"	color: #0096ff;",
		"}",
		".panel-qlist .panel-headings .heading-3-sub {",
		"	color: #111;",
		"}",
		".panel-header span {",
		"	color: #0096ff;",
		"}",
		"#page_panels > div > div.panel-wrapper.panel-wrapper-queuelist > div:nth-child(4) > div > div.panel-body.nano.has-scrollbar > div.nano-content > div > div > ul div {",
		"	color: #111 !important;",
		"}",
		".page-naboo-search .suggest-column .nano-card-item {",
		"	background-color: #1f1f1f;",
		"}",
		".page-naboo-search .suggest-column .nano-card-item:hover {",
		"	background-color: #343434;",
		"}",
		".page-naboo-search .suggest-column .nano-card-item:hover a {",
		"	color: #ff6400 !important;",
		"}",
		".modal-dialog, #modal-sharebox {",
		"	background-color: #191919 !important;",
		"}",
		".modal-body, .modal-footer {",
		"	background-color: #191919 !important;",
		"	color: #EEE !important;",
		"}",
		".modal-header {",
		"	color: #0096ff !important;",
		"	background-color: #191919 !important;",
		"	border-bottom-color: #000 !important;",
		"}",
		"#modal_sharebox .share-nav {",
		"	background-color: #0f0f0f !important;",
		"	padding-left: 20px;",
		"}",
		"#modal_sharebox .share-followers {",
		"	background-color: #191919;",
		"	padding-bottom: 0;",
		"}",
		"#modal_sharebox .share-nav-tabs.selected {",
		"	background-color: #0096FF;",
		"	color: #FFF;",
		"}",
		"#modal_sharebox .share-nav-tabs:hover {",
		"	background-color: #ff6400;",
		"	color: #000 !important;",
		"	font-weight: bold;",
		"}",
		"#modal_sharebox .share-nav-tabs {",
		"	border-radius: 5px 5px 0 0;",
		"	color: #EEE;",
		"	float: left;",
		"	line-height: 40px;",
		"	padding: 0 20px;",
		"	transition-duration: .15s;",
		"	transition-property: background-color;",
		"}",
		"#modal_sharebox .share-message {",
		"	color: #EEE;",
		"	background-color: #222;",
		"	border-color: #000;",
		"}",
		".form-control-static {",
		"	background-color: #222;",
		"	color: #0096ff;",
		"	border-color: #0096ff;",
		"}",
		"#modal_sharebox .modal-footer .btn-label {",
		"	color: #FFF;",
		"	cursor: default;",
		"	font-size: 11px;",
		"	font-weight: bold;",
		"	font-weight: 400;",
		"	padding-left: 0;",
		"	padding-right: 0;",
		"}",
		".btn-share:after {",
		"	-moz-filter: invert(100%);",
		"	-webkit-filter: invert(100%);",
		"	filter: invert(100%);",
		"}",
		"#page_feed .card {",
		"	background-color: #121212;",
		"	box-shadow: 0 1px 2px rgba(25, 25, 25, .15);",
		"	margin-top: 20px;",
		"	position: relative;",
		"	transition-duration: .15s;",
		"	transition-property: box-shadow;",
		"}",
		"#page_feed .footer {",
		"	display: block;",
		"	background-color: #222;",
		"	box-sizing: border-box;",
		"	height: 36px;",
		"	padding: 10px 20px;",
		"}",
		"#page_feed .footer > .btn-link + .btn {",
		"	border-left: 1px solid #000;",
		"	margin-left: 10px;",
		"	padding-left: 10px;",
		"}",
		"#page_feed .divider .divider-line {",
		"	background-color: #ff6400;",
		"	height: 1px;",
		"	margin-top: 13px;",
		"	position: absolute;",
		"	width: 100%;",
		"	z-index: 1;",
		"}",
		"#page_feed .divider .divider-text {",
		"	color: #FFF;",
		"	background-color: #ff6400;",
		"	font-size: 11px;",
		"	padding: 0 10px;",
		"	display: inline-block;",
		"	position: relative;",
		"	z-index: 2;",
		"}",
		"#page_feed .card-trending .progress-bar-inner {",
		"	background-color: #0096ff;",
		"	height: 40px;",
		"	left: 0;",
		"	position: absolute;",
		"	top: 0;",
		"	width: 0;",
		"	z-index: 20;",
		"}",
		"#page_feed .card-trending .load-bar-inner {",
		"	background-color: #000;",
		"	height: 40px;",
		"	opacity: .5;",
		"	position: absolute;",
		"	top: 0;",
		"	left: 0;",
		"	width: 0;",
		"	z-index: 10;",
		"}",
		"#page_feed .card-trending .waveform {",
		"	background-size: 100% 40px;",
		"	height: 40px;",
		"	left: 0;",
		"	position: absolute;",
		"	top: 0;",
		"	width: 100%;",
		"	z-index: 30;",
		"	-moz-filter: invert(100%) hue-rotate(180deg);",
		"	-webkit-filter: invert(100%) hue-rotate(180deg);",
		"	filter: invert(100%) hue-rotate(180deg);",
		"}",
		"#page_feed .card-trending .waveform-design {",
		"	height: 40px;",
		"	left: 0;",
		"	position: absolute;",
		"	top: 0;",
		"	width: 100%;",
		"	z-index: 40;",
		"	-moz-filter: invert(100%) hue-rotate(180deg);",
		"	-webkit-filter: invert(100%) hue-rotate(180deg);",
		"	filter: invert(100%) hue-rotate(180deg);",
		"}",
		".popover-header > .cell.cell-thumbnail * img, .page-panels .panel-wrapper .nano-card-picture * img, .notifications-item-media-picture * img:not([src*=\"http://e-cdn-images.deezer.com/images/playlist/d41d8cd98f00b204e9800998ecf8427e/56x56-000000-80-0-0.jpg\"]), #panel-lyrics {",
		"	-moz-filter: invert(100%) hue-rotate(180deg);",
		"	-webkit-filter: invert(100%) hue-rotate(180deg);",
		"	filter: invert(100%) hue-rotate(180deg);",
		"}",
		".panel-lyrics.has-lyrics .nano-content {",
		"	-webkit-mask-image: linear-gradient(to bottom,rgba(10,10,10,0) 0,#0a0a0a 20%,#0a0a0a 80%,rgba(10,10,10,0) 100%);",
		"	mask-image: linear-gradient(to bottom,rgba(10,10,10,0) 0,#0a0a0a 20%,#0a0a0a 80%,rgba(10,10,10,0) 100%);",
		"}",
		".page-sidebar .player-cover.has-contextmenu .player-progress .progress-length, .page-sidebar .player-cover.has-contextmenu .player-progress .progress-time, .page-sidebar .player-cover:hover .player-progress .progress-length, .page-sidebar .player-cover:hover .player-progress .progress-time {",
		"	background-color: transparent !important;",
		"	color: #ff6400;",
		"	font-weight: bold;",
		"}",
		".alert-info {",
		"	background-color: #aa0000;",
		"	border-color: #000;",
		"	color: #FFF;",
		"}",
		".popover .heading-4-sub, .page-panels .panel-wrapper .heading-4-sub {",
		"	color: #000;",
		"}",
		".panel-lyrics .panel-close .icon {",
		"	color: #FFF;",
		"}",
		".panel-lyrics {",
		"	background-color: #000;",
		"	background-position: center center;",
		"	background-repeat: no-repeat;",
		"	background-size: cover;",
		"}",
		".panel-lyrics .lyrics-line {",
		"	color: #FFF;",
		"}",
		".panel-lyrics .lyrics-line-active {",
		"	color: #0096ff;",
		"	-webkit-text-stroke: #0096ff .7px;",
		"	border-radius: 30px;",
		"	box-shadow: 0 0 2px 2px #000;",
		"	background: rgba(25,25,25,0.9);",
		"	background: radial-gradient(circle farthest-corner at center center, rgba(25,25,25,0.9) 15%, rgba(0,0,0,0.5) 100%);",
		"	background: -webkit-radial-gradient(circle farthest-corner at center center, rgba(25,25,25,0.9) 15%, rgba(0,0,0,0.5) 100%);",
		"	background: -moz-radial-gradient(circle farthest-corner at center center, rgba(25,25,25,0.9) 15%, rgba(0,0,0,0.5) 100%);",
		"}",
		".panel-lyrics .lyrics-infos .lyrics-line-active:hover {",
		"	background-color: #191919;",
		"	color: #ff6400 !important;",
		"}",
		".panel-lyrics.has-synchro .lyrics-content .lyrics-line-active:focus, .panel-lyrics.has-synchro .lyrics-content .lyrics-line-active:hover {",
		"	background-color: #191919;",
		"	color: #ff6400 !important;",
		"}",
		".panel-lyrics.has-synchro .lyrics-content .lyrics-line, .panel-lyrics.has-synchro .lyrics-content .lyrics-line:hover {",
		"	border-radius: 30px;",
		"}",
		".panel-lyrics.has-synchro .lyrics-content .lyrics-line:hover {",
		"	-webkit-text-stroke: #ff6400 .7px;",
		"}",
		".panel-lyrics .panel-lyrics-overlay {",
		"	background-color: #191919;",
		"	bottom: 0;",
		"	content: \"\";",
		"	left: 0;",
		"	opacity: .60;",
		"	position: absolute;",
		"	right: 0;",
		"	top: 0;",
		"}",
		".page-contextmenu .menu-item.link:hover {",
		"	background-color: #ff6400;",
		"}",
		".thumbnail .action-item-btn.action-active .icon-love {",
		"	color: #ff0000;",
		"}",
		"#page_account .account-wrapper {",
		"	background: #0a0a0a;",
		"}",
		"#page_account .form-control {",
		"	background-color: #000;",
		"	border: 1px solid #333;",
		"	transition-duration: .15s;",
		"	transition-property: background-color, border, color;",
		"	color: #fff;",
		"	font-weight: bold;",
		"}",
		"#page_account .account-delete {",
		"	background: #111;",
		"	border-top: 1px solid #343434;",
		"	color: #ff0000;",
		"	border-bottom-left-radius: 5px;",
		"	border-bottom-right-radius: 5px;",
		"}",
		"#page_account .account-delete .link-remove {",
		"	color: #ff0000;",
		"}",
		".alert-success {",
		"	background-color: #222;",
		"	border-color: #468847;",
		"	color: #468847;",
		"}",
		"#page_account .account-social .social-table {",
		"	border: 1px solid #333;",
		"	border-collapse: collapse;",
		"	width: 100%;",
		"}",
		"#page_account .account-social .social-cell {",
		"	background-color: #111;",
		"	border: 1px solid #333;",
		"	padding: 15px;",
		"	vertical-align: middle;",
		"	width: 20%;",
		"}",
		"#page_account .account-social .social-options-item {",
		"	background-color: #222;",
		"}",
		"#page_account .account-social .social-options-item:nth-child(2n) {",
		"	background-color: #181818;",
		"}",
		"#page_account .account-social .social-platform-unlink {",
		"	color: #fff;",
		"	transition-duration: .15s;",
		"	transition-property: color;",
		"}",
		"#page_account .account-social .social-platform-unlink::before {",
		"	border-color: transparent transparent #ff6400;",
		"	border-style: solid;",
		"}",
		".channel-horizontalgrid-control {",
		"	border: 1px solid #fff;",
		"	color: #fff;",
		"	background-color: #0096ff;",
		"	transition-duration: .15s;",
		"	transition-property: background-color, color, opacity;",
		"}",
		".channel-horizontalgrid-control:hover:not(.disabled) {",
		"	background-color: #ff6400;",
		"	color: #000;",
		"}",
		".thumbnail-viewmore {",
		"	background-color: #111;",
		"	border: solid 1px #444;",
		"	border-radius: 4px;",
		"	box-shadow: 0 1px 2px 0 rgba(25, 25, 34, .24);",
		"	color: #323232;",
		"	transition-duration: .15s;",
		"	transition-property: color;",
		"}",
		".catalog-content .dropdown .dropdown-menu, .user-section .dropdown .dropdown-menu {",
		"	background: #000 !important;",
		"	border: 1px solid #2e2e2e;",
		"	box-shadow: 0 1px 5px rgba(245, 245, 245, .2);",
		"}",
		".catalog-content .dropdown .dropdown-menu > li > a, .catalog-content .dropdown .dropdown-menu > li > button, .user-section .dropdown .dropdown-menu > li > a, .user-section .dropdown .dropdown-menu > li > button {",
		"	background-color: #000;",
		"	box-sizing: border-box;",
		"	color: #0096ff;",
		"	transition-duration: .15s;",
		"	transition-property: background-color, color;",
		"}",
		" :not(.datagrid-table) ~ .icon-chevron-down {",
		"	color: #000 !important;",
		"}",
		".btn:hover :not(.datagrid-table) ~ .icon-chevron-down {",
		"	color: #FFF !important;",
		"}",
		".btn-app:hover, .btn-default:hover, .btn-group > .btn-label:hover, .btn-slide:hover, .btn-telco:hover, .btn-upload:hover .btn, .selectbox.opened .btn-group > .dropdown-toggle.btn-label, .selectbox.opened .dropdown-toggle.btn-app, .selectbox.opened .dropdown-toggle.btn-default, .selectbox.opened .dropdown-toggle.btn-slide, .selectbox.opened .dropdown-toggle.btn-telco {",
		"	background-color: #ff6400;",
		"}",
		".catalog-content .dropdown .dropdown-menu > li > a:hover, .catalog-content .dropdown .dropdown-menu > li > button:hover, .user-sectiont .dropdown .dropdown-menu > li > a:hover, .user-section .dropdown .dropdown-menu > li > button:hover {",
		"	background-color: #222;",
		"	color: #000;",
		"}",
		".page-contextmenu .menu-item {",
		"	-webkit-text-stroke: .6px;",
		"	color: #525252;",
		"}",
		".naboo-catalog .has-alternate-bg {",
		"	background-color: #0a0a0a;",
		"}",
		".naboo-catalog .catalog-tab-box {",
		"	-webkit-box-shadow: none;",
		"	box-shadow: none;",
		"}",
		".page-loader {",
		"	-webkit-backface-visibility: hidden;",
		"	backface-visibility: hidden;",
		"	background-color: #0a0a0a;",
		"	height: 4px;",
		"	left: 0;",
		"	overflow: hidden;",
		"	position: fixed;",
		"	right: 0;",
		"	top: 0;",
		"	-webkit-transform: translateY(-4px);",
		"	-ms-transform: translateY(-4px);",
		"	transform: translateY(-4px);",
		"	z-index: 1000;",
		"	transition-duration: .15s;",
		"	transition-property: -webkit-transform;",
		"	transition-property: transform;",
		"	transition-property: transform,-webkit-transform;",
		"}",
		".datagrid {",
		"	background-color: #0a0a0a;",
		"	color: #ccc;",
		"	display: table;",
		"	font-family: \"Open Sans\", Arial, sans-serif;",
		"	font-size: 14px;",
		"	font-weight: 400;",
		"	table-layout: fixed;",
		"	width: 100%;",
		"}",
		".datagrid-row {",
		"	-webkit-align-items: center;",
		"	-ms-flex-align: center;",
		"	align-items: center;",
		"	border-radius: 4px;",
		"	box-sizing: border-box;",
		"	display: -webkit-flex;",
		"	display: -ms-flexbox;",
		"	display: flex;",
		"	-webkit-flex-wrap: nowrap;",
		"	-ms-flex-wrap: nowrap;",
		"	flex-wrap: nowrap;",
		"	height: 52px;",
		"	padding: 0 16px;",
		"	position: relative;",
		"	transition-duration: .15s;",
		"	transition-property: background-color;",
		"}",
		".datagrid-header .is-sortable .icon,.datagrid-header .is-sortable .svg-icon {",
		"	color: #0096ff;",
		"	line-height: 52px;",
		"	margin-left: 5px;",
		"	opacity: 0;",
		"	position: relative;",
		"	top: 2px;",
		"	transition-duration: .15s;",
		"	transition-property: opacity;",
		"}",
		".datagrid-header .datagrid-row::before, .datagrid-row::before {",
		"	background-color: #333;",
		"	height: 1px;",
		"	left: 6px;",
		"	position: absolute;",
		"	right: 6px;",
		"}",
		".no-flexbox .datagrid-cell {",
		"	display: table-cell;",
		"	line-height: 36px;",
		"	vertical-align: middle",
		"}",
		".datagrid-label-main {",
		"	color: #eee;",
		"}",
		".datagrid-label {",
		"	color: #ccc;",
		"	transition-duration: .15s;",
		"	transition-property: color;",
		"}",
		".datagrid-row.song.active {",
		"	background-color: rgba(255, 100, 0, .7);",
		"	color: #eee;",
		"}",
		".datagrid-row.active .datagrid-label, .datagrid-row.active .datagrid-label-sub {",
		"	color: #fff !important;",
		"}",
		".datagrid-row:hover {",
		"	background-color: #333;",
		"}",
		".datagrid-header .datagrid-row:hover {",
		"	background-color: #333;",
		"	cursor: default;",
		"}",
		".datagrid-label:hover {",
		"	color: #ff6400;",
		"	-webkit-text-stroke: 0.4px;",
		"	cursor: pointer;",
		"}",
		".datagrid-header .datagrid-label {",
		"	color: #fff;",
		"}",
		".datagrid-action {",
		"	border-radius: 50%;",
		"	color: #eee;",
		"	cursor: pointer;",
		"	display: block;",
		"	font-size: 14px;",
		"	height: 28px;",
		"	line-height: 28px;",
		"	text-align: center;",
		"	width: 28px;",
		"	transition-duration: .15s;",
		"	transition-property: background-color, color;",
		"}",
		".datagrid-badge-unseen {",
		"	background-color: #0096ff;",
		"	border-radius: 50%;",
		"	height: 8px;",
		"	position: absolute;",
		"	width: 8px;",
		"}",
		"icon-stack-hover .icon {",
		"	color: #ff6400;",
		"	transition-duration: .15s;",
		"	transition-property: opacity;",
		"}",
		".cell-play:hover {",
		"	-moz-filter: invert(100%) hue-rotate(180deg) !important;",
		"	-webkit-filter: invert(100%) hue-rotate(180deg) !important;",
		"	filter: invert(100%) hue-rotate(180deg) !important;",
		"}",
		".cell-play:hover .play-active {",
		"	-moz-filter: invert(100%) hue-rotate(0deg) !important;",
		"	-webkit-filter: invert(100%) hue-rotate(0deg) !important;",
		"	filter: invert(100%) hue-rotate(0deg) !important;",
		"}",
		".datagrid-header .datagrid-label:hover/* .cell-play:hover*/ {",
		"	color: #ff6400 !important;",
		"}",
		".icon.active {",
		"	color: #0096ff !important;",
		"}",
		".icon-love.active {",
		"	color: #ff0000 !important;",
		"}",
		".datagrid-row.song.active .icon-love.active {",
		"	color: #000 !important;",
		"}",
		".datagrid-row.song.active .datagrid-action:hover .icon-love.active {",
		"	color: #ff0000 !important;",
		"}",
		".datagrid-row .datagrid-action:hover .icon-love.active {",
		"	color: #fff !important;",
		"}",
		".banner-header {",
		"	background-color: #0a0a0a;",
		"	padding: 0;",
		"	position: relative;",
		"}",
		".navbar-nav > li > a, .navbar-nav > li > button {",
		"	background-color: transparent;",
		"	border-bottom: 3px solid transparent;",
		"	box-sizing: border-box;",
		"	color: #999;",
		"	display: block;",
		"	font-family: \"Open Sans\", Arial, sans-serif;",
		"	font-weight: 700;",
		"	height: 50px;",
		"	letter-spacing: .5px;",
		"	padding: 0 15px;",
		"	transition-duration: .15s;",
		"	transition-property: border-color, color;",
		"}",
		".naboo-catalog .has-white-bg {",
		"	background-color: #0a0a0a;",
		"}",
		".carousel-control {",
		"	background-color: #0096ff;",
		"	border: 1px solid #444;",
		"	color: #fff;",
		"	cursor: pointer;",
		"	padding: 7px;",
		"	text-align: center;",
		"	transition-duration: .15s;",
		"	transition-property: background-color, color, opacity;",
		"}",
		".carousel-control:hover:not(.disabled) {",
		"	background-color: #ff6400;",
		"	color: #000;",
		"}",
		".slide .slide-background {",
		"	background-color: #000;",
		"	border-radius: 4px;",
		"	height: 100%;",
		"	position: relative;",
		"	width: 100%;",
		"}",
		".slide {",
		"	border-radius: 4px;",
		"	box-shadow: 0px 0px 5px 1px rgba(150, 150, 150, 0.25);",
		"	color: #ddd;",
		"	display: inline-block;",
		"	font-family: \"Open Sans\", Arial, sans-serif;",
		"	max-height: 100%;",
		"	max-width: 100%;",
		"	opacity: 1;",
		"	overflow: hidden;",
		"	position: relative;",
		"	vertical-align: top;",
		"	transition-duration: .15s;",
		"	transition-property: opacity, box-shadow;",
		"}",
		".slide .slide-text .subtitle, .slide .slide-text .subtitle .link {",
		"	color: #999;",
		"}",
		".large-card-inner-infos .heading-label {",
		"	color: #999;",
		"}",
		".thumbnail-caption .caption-released {",
		"	color: #999;",
		"}",
		".slide .slide-btn {",
		"	border: 1px solid #333;",
		"	color: #eee;",
		"	font-size: .7em;",
		"	font-weight: 700;",
		"	margin-top: 1em;",
		"	opacity: 1;",
		"	padding: .4em .9em;",
		"	transition-duration: .15s;",
		"	transition-property: opacity, background-color, color;",
		"}",
		".slide .slide-btn:hover {",
		"	background-color: #ff6400;",
		"	border-color: transparent;",
		"	color: #000;",
		"}",
		".sticker-default {",
		"	background-color: #ff6400;",
		"}",
		"#page_feed .card-release-album .visual {",
		"	border-left: 1px solid #343434;",
		"	float: right;",
		"	height: 352px;",
		"	width: 477px;",
		"}",
		"#page_feed .card-algo-playlist .visual {",
		"	border-right: 1px solid #343434;",
		"	float: left;",
		"	height: 250px;",
		"	width: 250px;",
		"}",
		"#page_feed .card-trending .visual {",
		"	border-right: 1px solid #343434;",
		"	float: left;",
		"	height: 250px;",
		"	width: 250px;",
		"}",
		".btn-tag {",
		"	color: #000;",
		"	-webkit-text-stroke: #000 .4px;",
		"}",
		".btn-tag:hover {",
		"	color: #fff !important;",
		"	-webkit-text-stroke: #fff 0.0px;",
		"}",
		".page-sidebar .player-track-title .player-track-link {",
		"	color: #fff !important;",
		"	text-shadow: 0 0 3px #0096ff;",
		"}",
		".page-sidebar .player-track-title .player-track-link:hover {",
		"	color: #ff6400 !important;",
		"	-webkit-text-stroke: #ff6400 0.6px;",
		"	text-shadow: 0 0 3px #000;",
		"}",
		".page-sidebar .player-track-artist .player-track-link {",
		"	color: #0096ff !important;",
		"	-webkit-text-stroke: #0096ff 0.6px;",
		"	text-shadow: 0 0 3px #000;",
		"}",
		".page-sidebar .player-track-artist .player-track-link:hover {",
		"	color: #ff6400 !important;",
		"	-webkit-text-stroke: #ff6400 0.6px;",
		"	text-shadow: 0 0 3px #000;",
		"}",
		".page-naboo-search .datagrid-container {",
		"	background-color: #0a0a0a;",
		"}",
		".tooltip {",
		"	background-color: rgba(0,0,0,1.0) !important;",
		"	color: #fff;",
		"}",
		".datagrid-action:hover {",
		"	background-color: #ff6400;",
		"	color: #000 !important;",
		"}",
		".datagrid-row.song.active .datagrid-action:not([aria-label*=\"Add to favourite tracks\"]):hover {",
		"	color: #0096ff !important;",
		"}",
		".datagrid-row.song.active .datagrid-action:hover {",
		"	background-color: #000;",
		"}",
		".datagrid-row.song.active .datagrid-action[aria-label*=\"Add to favourite tracks\"]:hover {",
		"	color: #fff !important;",
		"}",
		".icon-stack-hover:after {",
		"	color: #0096ff;",
		"}",
		".datagrid-row.song.active .icon-stack-hover .icon {",
		"	color: #fff;",
		"}",
		".datagrid-row.song.active .icon-stack-hover:after {",
		"	color: #000;",
		"}",
		".datagrid-row.song.active .datagrid-label:hover, .datagrid-row.song.active .datagrid-label-sub:hover {",
		"	color: #000 !important;",
		"	-webkit-text-stroke: #000 0.6px;",
		"}",
		".nano-card-picture {",
		"	border-right: none;",
		"}",
		".popover-header .heading-4 a, .popover-header .heading-4-sub a {",
		"	color: #0096ff;",
		"	-webkit-text-stroke: #0096ff 0.4px;",
		"}",
		".popover-header .heading-4 a:hover, .popover-header .heading-4-sub a:hover {",
		"	-webkit-text-stroke: 0.4px;",
		"}",
		".color-primary {",
		"	color: #0096ff !important;",
		"}",
		".btn-view-more:after, .icon-chevron-right:before, .link-animated:after {",
		"	content: none;",
		"}",
		".page-panels .panel-overlay {",
		"	background-color: #0a0a0a;",
		"	bottom: 0;",
		"	left: 0;",
		"	opacity: 0;",
		"	position: fixed;",
		"	right: 0;",
		"	top: 0;",
		"	z-index: 200;",
		"	transition-duration: .15s;",
		"	transition-property: opacity;",
		"}",
		".page-panels .panel-container.opened .panel-overlay {",
		"	opacity: .6;",
		"}",
		".page-sidebar .search-control {",
		"	background-color: #e1e1e1;",
		"	border: 0;",
		"	border-radius: 3px;",
		"	box-sizing: border-box;",
		"	color: #424242;",
		"	display: block;",
		"	font-family: \"Lucida Grande\",Arial,sans-serif;",
		"	font-size: 12px;",
		"	height: 32px;",
		"	line-height: 1.33333333;",
		"	padding: 8px 40px 8px 12px;",
		"	width: 100%;",
		"	transition-duration: .15s;",
		"	transition-property: background-color,color;",
		"}",
		".page-sidebar .player-controls>.controls>li>.control.disabled, .page-sidebar .player-controls>.controls>li>.control.disabled:hover, .page-sidebar .player-controls>.controls>li>.control[disabled], .page-sidebar .player-controls>.controls>li>.control[disabled]:hover {",
		"	color: #525252;",
		"	cursor: default;",
		"}",
		".modal-backdrop {",
		"	background-color: #191919;",
		"	height: 100%;",
		"	left: 0;",
		"	opacity: 0;",
		"	position: fixed;",
		"	table-layout: fixed;",
		"	top: 0;",
		"	width: 100%;",
		"	z-index: 8010;",
		"	transition-duration: .15s;",
		"	transition-property: opacity;",
		"}",
		".modal.opened .modal-backdrop {",
		"	opacity: .8;",
		"}",
		"#notify {",
		"	background-color: #0096ff;",
		"	background-color: rgba(0,150,255,.8);",
		"	display: none;",
		"	left: 0;",
		"	position: fixed;",
		"	text-align: center;",
		"	top: 0;",
		"	width: 100%;",
		"	z-index: 1000;",
		"}",
		".btn-share {",
		"	border: none !important;",
		"}",
		".btn-share::after {",
		"	background-color: #f8f8f8;",
		"	border-bottom-right-radius: 3px;",
		"	border-top-right-radius: 3px;",
		"	color: #323232;",
		"	font-family: \"Deezer Icons\",sans-serif;",
		"	font-size: 16px;",
		"	height: 24px;",
		"	line-height: 24px;",
		"	position: absolute;",
		"	right: 0;",
		"	top: 0;",
		"	width: 28px;",
		"	transition-duration: .15s;",
		"	transition-property: background-color;",
		"}",
		".btn-share:hover::after {",
		"	background-color: #0096ff;",
		"	border-bottom-right-radius: 3px;",
		"	border-top-right-radius: 3px;",
		"	color: #fff;",
		"	font-family: \"Deezer Icons\",sans-serif;",
		"	font-size: 16px;",
		"	height: 24px;",
		"	line-height: 24px;",
		"	position: absolute;",
		"	right: 0;",
		"	top: 0;",
		"	width: 28px;",
		"	transition-duration: .15s;",
		"	transition-property: background-color;",
		"}",
		".modal-close {",
		"	color: #777;",
		"	font-size: 16px;",
		"	position: absolute;",
		"	right: 20px;",
		"	top: 20px;",
		"	z-index: 1",
		"}",
		".modal-close:hover {",
		"	color: #ff0000;",
		"	-webkit-text-stroke: #ff0000 .7px;",
		"	text-shadow: 0 0 2px #000;",
		"}",
		".panel-settings .heading-bordered {",
		"	border-bottom: 1px solid #9b9b9b;",
		"}",
		".checkbox.checked:before {",
		"	background-color: #0096ff;",
		"	border-color: #0096ff;",
		"}",
		".checkbox.checked:hover:before {",
		"	background-color: #ff6400;",
		"	border-color: #ff6400;",
		"}",
		".panel-settings .checkbox .checkbox-tick {",
		"	fill: #000;",
		"}",
		".panel-settings .checkbox:hover .checkbox-tick {",
		"	fill: #fff;",
		"}",
		".panel-settings .nano-card-link.animate-wobble .animate-wobble-target {",
		"	fill: #000;",
		"}",
		".panel-settings .nano-card-link.animate-wobble:hover .animate-wobble-target {",
		"	fill: #ff6400;",
		"}",
		".nano-card-link:focus, .nano-card-link:hover {",
		"	background-color: #e5e5e5;",
		"	outline: 0;",
		"}",
		".panel-settings .rounded-icon-user {",
		"	background-color: #0096ff;",
		"}",
		".panel-settings .rounded-icon-help {",
		"	background-color: #509900;",
		"}",
		".panel-settings .rounded-icon-code {",
		"	background-color: #ee99ff;",
		"}",
		".panel-settings .rounded-icon {",
		"	color: #000;",
		"}",
		"button[data-type=\"log_out\"] .label, .btn-clear .label {",
		"	color: #000 !important;",
		"	-webkit-text-stroke: #000 .6px;",
		"}",
		"button[data-type=\"log_out\"]:hover .label,  .btn-clear:hover .label  {",
		"	color: #fff !important;",
		"	-webkit-text-stroke: #fff 0px;",
		"}",
		":focus {",
		"	outline: none;",
		"}",
		".panel-settings .slider-bar-handler {",
		"	background-color: #ff6400;",
		"	border: 1px solid #dedede;",
		"}",
		".panel-settings .slider-bar {",
		"	background-color: #dedede;",
		"}",
		".panel-settings .slider-label {",
		"	color: #888;",
		"}",
		".nano>.nano-pane>.nano-slider {",
		"	background-color: #c2c2c2;",
		"}",
		".nano>.nano-pane>.nano-slider:hover {",
		"	background-color: #0096ff;",
		"}",
		".nano-card-link .icon {",
		"	color: #c2c2c2;",
		"}",
		".nano-card-link:hover .icon {",
		"	color: #444;",
		"	-webkit-text-stroke: #444 .5px;",
		"}",
		".panel-search-history .heading-bordered {",
		"	border-bottom: 1px solid #9b9b9b;",
		"}",
		".page-sidebar .profile .profile-settings {",
		"	color: #a2a2a2;",
		"	cursor: pointer;",
		"	margin-top: -18px;",
		"	padding: 10px;",
		"	position: absolute;",
		"	right: 4px;",
		"	top: 50%;",
		"	transition-duration: .15s;",
		"	transition-property: color;",
		"}",
		".page-sidebar .profile .profile-settings.active-panel, .page-sidebar .profile .profile-settings:focus, .page-sidebar .profile .profile-settings:hover {",
		"	color: #ff6400;",
		"}",
		".nano-card-item {",
		"	background-color: #f8f8f8;",
		"}",
		".nano-card-link {",
		"	background-color: transparent;",
		"}",
		".nano-card-item.has-contextmenu, .nano-card-item:hover {",
		"	background-color: #efefef;",
		"}",
		".nano-card-options .option {",
		"	color: #777;",
		"	display: inline-block;",
		"	transition-duration: .15s;",
		"	transition-property: color;",
		"}",
		".nano-card-options .option:hover {",
		"	color: #ff6400;",
		"}",
		".page-sidebar .player-progress .progress-seek-overlay {",
		"	background-color: #2229;",
		"	opacity: 0.25;",
		"	-moz-backdrop-filter: grayscale(100%) contrast(130%) brightness(70%);",
		"	-webkit-backdrop-filter: grayscale(100%) contrast(130%) brightness(70%);",
		"	backdrop-filter: grayscale(100%) contrast(130%) brightness(70%);",
		"}",
		".page-panels .panel-body:not(.lyrics-panel-body), .nano-card-item {",
		"	background-color: #f8f8f8;",
		"}",
		".panel-apps .app-suggest {",
		"	background-color: #f8f8f8;",
		"}",
		".panel-notifications .notifications-item {",
		"	background-color: #f8f8f8;",
		"	border-bottom: 1px solid #efefef;",
		"}",
		".panel-notifications .notifications-item:hover {",
		"	background-color: #efefef;",
		"}",
		"#page_feed .footer .time {",
		"	color: #ccc;",
		"}",
		".thumbnail .action-item-btn, .slide.slide-cut .slide-play-icon .action-item-btn {",
		"	background-color: #000;",
		"	color: #fff;",
		"	transition-property: opacity,transform,-webkit-transform,background-color,color,box-shadow;",
		"	box-shadow: 0 0 2px 2px #0096ff;",
		"}",
		".thumbnail .action-item-btn:hover, .slide.slide-cut .slide-play-icon .action-item-btn:hover {",
		"	background-color: #0096ff;",
		"	color: #fff;",
		"	box-shadow: 0 0 2px 2px #000;",
		"}",
		".dropdown .dropdown-menu>li>a:hover, .dropdown .dropdown-menu>li>button:hover {",
		"	background-color: #f8f8f8;",
		"	color: #323232;",
		"}",
		".catalog-header .header-info .heading-link {",
		"	color: #ccc;",
		"}",
		".page-panels .panel-wrapper .panel-lyrics .heading-4-sub.heading-inverse {",
		"	color: #ff6400;",
		"	-webkit-text-stroke: #ff6400 .5px;",
		"	text-shadow: 0 0 2px #000;",
		"}",
		".page-panels .panel-wrapper .panel-lyrics .heading-4.heading-inverse:hover {",
		"	color: #ff6400;",
		"	-webkit-text-stroke: #ff6400 .5px;",
		"	text-shadow: 0 0 2px #000;",
		"}",
		".page-panels .panel-wrapper .panel-lyrics .heading-4-sub.heading-inverse .lyrics-artist-link {",
		"	color: #0096ff;",
		"	-webkit-text-stroke: #0096ff .5px;",
		"	text-shadow: 0 0 2px #000;",
		"}",
		".page-panels .panel-wrapper .panel-lyrics .heading-4-sub.heading-inverse .lyrics-artist-link:hover {",
		"	color: #ff6400;",
		"	-webkit-text-stroke: #ff6400 .5px;",
		"	text-shadow: 0 0 2px #000;",
		"}",
		".is-favorite .svg-icon {",
		"	-webkit-filter: drop-shadow(0px 0px 5px #000);",
		"	-moz-filter: drop-shadow(0px 0px 5px #000);",
		"	filter: drop-shadow(0px 0px 5px #000);",
		"}",
		".is-favorite {",
		"	color: #ff0000;",
		"}",
		".datagrid-action:hover .is-favorite .svg-icon {",
		"	color: #fff !important;",
		"}",
		".btn-favorite>.action-active .icon-love, .btn-favorite>.action-active .svg-icon-love {",
		"	color: #ff1e1e;",
		"}",
		".btn-app .icon, .btn-app .svg-icon, .btn-default .icon, .btn-default .svg-icon, .btn-group>.btn-label .icon, .btn-group>.btn-label .svg-icon, .btn-slide .icon, .btn-slide .svg-icon, .btn-telco .icon, .btn-telco .svg-icon {",
		"	color: #fff;",
		"}",
		".svg-icon.active, .svg-icon.is-active {",
		"	fill: #0096ff;",
		"}",
		".cell-love .svg-icon.active, .cell-love .svg-icon.is-active {",
		"	fill: #ff1e1e;",
		"}",
		".cell-love .datagrid-action:hover .svg-icon.active, .cell-love .datagrid-action:hover .svg-icon.is-active {",
		"	fill: #ff1e1e;",
		"}",
		".cell-love .datagrid-action:hover .svg-icon-love-outline.is-active, .cell-love .datagrid-action:hover .svg-icon-love-outline.is-active {",
		"	color: #fff;",
		"}",
		".cell-love .datagrid-action:hover .svg-icon-love-outline.is-active .svg-path, .cell-love .datagrid-action:hover .svg-icon-love-outline.is-active .svg-path {",
		"	fill: #ff1e1e;",
		"}",
		".cell-love .datagrid-action:hover .svg-icon-love-outline, .cell-love .datagrid-action:hover .svg-icon-love-outline {",
		"	color: #ddd;",
		"}",
		".cell-love .datagrid-action:hover .svg-icon-love-outline .svg-path, .cell-love .datagrid-action:hover .svg-icon-love-outline .svg-path {",
		"	fill: #444;",
		"}",
		".datagrid-row.song.active .cell-love .svg-icon.active, .datagrid-row.song.active .cell-love .svg-icon.is-active {",
		"	fill: #ff1e1e;",
		"	color: #000;",
		"	filter: drop-shadow(0px 0px 2px #000);",
		"}",
		".datagrid-row.song.active .cell-love .datagrid-action:hover .svg-icon.active, .datagrid-row.song.active .cell-love .datagrid-action:hover .svg-icon.is-active {",
		"	fill: #ff1e1e;",
		"	color: #fff;",
		"	filter: drop-shadow(0px 0px 2px #000);",
		"}",
		".datagrid-row.song.active .cell-love .svg-icon.active .svg-path, .datagrid-row.song.active .cell-love .svg-icon.is-active .svg-path {",
		"	fill: #ff1e1e;",
		"}",
		".svg-icon-love-outline.is-active {",
		"	color: #ff1e1e;",
		"	fill: none;",
		"}",
		".svg-icon-love-outline.is-active .svg-path {",
		"	fill: none;",
		"	fill-rule: nonzero;",
		"}",
		".navbar-item.active .navbar-link {",
		"	border-color: #0096ff;",
		"	color: #ff6400;",
		"}",
		"#page_account .account-labs .lab-title {",
		"	color: #ccc;",
		"}",
		"#page_account .account-labs .lab-name {",
		"	color: #0096ff;",
		"}",
		"#page_account .heading-2 {",
		"	color: #eee;",
		"}",
		"#page_profile .dropdown .dropdown-menu>li>a:hover, #page_profile .dropdown .dropdown-menu>li>button:hover {",
		"	background-color: #222;",
		"	color: #ff6400;",
		"}",
		"#page_profile .dropdown .dropdown-menu, #page_profile .dropdown .dropdown-menu>li>a, #page_profile .dropdown .dropdown-menu>li>button {",
		"	background-color: transparent;",
		"}",
		"#page_profile .dropdown .dropdown-menu>li>a, #page_profile .dropdown .dropdown-menu>li>button {",
		"	color: #ccc;",
		"}",
		"#page_profile .dropdown .dropdown-menu {",
		"	border-top: 1px solid #636363;",
		"	border-left: 1px solid #636363;",
		"	border-right: 1px solid #636363;",
		"	border-bottom: 1px solid #636363;",
		"}",
		".datagrid-header .datagrid-row:after {",
		"	background-color: transparent;",
		"	box-shadow: 0px -3px 0px 1px #0096ff;",
		"	filter: drop-shadow(0px -3px .1px #ccc);",
		"	backdrop-filter: invert(10%);",
		"	height: 0px;",
		"	left: 6px;",
		"	position: absolute;",
		"	right: 6px;",
		"	opacity: .7;",
		"	z-index: 100;",
		"}",
		".datagrid-header .datagrid-row:hover:after {",
		"	background-color: #333;",
		"	transition-duration: .15s;",
		"	transition-property: background-color;",
		"}",
		".datagrid-row:after {",
		"	background-color: #333;",
		"	transition-duration: .15s;",
		"	transition-property: background-color;",
		"}",
		".page-notifications>.notification {",
		"	background-color: #0096ff;",
		"}",
		".page-notifications>.notification>h2 {",
		"	color: #fff;",
		"	text-align: center;",
		"}",
		"#page_profile {",
		"	background-color: #0a0a0a;",
		"}",
		"#page_profile .dropdown .dropdown-menu, #page_profile .dropdown .dropdown-menu>li>a, #page_profile .dropdown .dropdown-menu>li>button {",
		"	background-color: #0a0a0a;",
		"}",
		".datagrid-divider .datagrid-row {",
		"	background-color: #0a0a0a;",
		"	color: #ff6400;",
		"}",
		".datagrid-divider .datagrid-row:hover {",
		"	background-color: #333;",
		"}",
		".datagrid-row.has-contextmenu/* .datagrid-row:hover*/ {",
		"	background-color: #222;",
		"}",
		"#page_appstudio .app-header {",
		"    background-color: #0a0a0a;",
		"}",
		"#page_appstudio .app-filters {",
		"    border-top: 1px solid #636363;",
		"}",
		"#page_appstudio .app-picture {",
		"    border-bottom: 1px solid #636363;",
		"}",
		"#page_appstudio div.app-picture .btn:hover .label {",
		"	color: #000;",
		"	-webkit-text-stroke: #000 .5px;",
		"}",
		"#page_appstudio .app-filter-item {",
		"	color: #aaa;",
		"}",
		"#page_appstudio .app-meta {",
		"	color: #aaa;",
		"}",
		"#page_appstudio .app-meta-link {",
		"	color: #aaa;",
		"}",
		"#page_account .account-apps .app-name {",
		"	color: #ccc;",
		"}",
		"#page_account .account-labs .lab-cell {",
		"	border-bottom: 1px solid #343434;",
		"}",
		"#page_account .account-labs .lab-info {",
		"	color: #aaa;",
		"}",
		".panel-notifications .btn-facebook:after, .panel-notifications .btn-googleplus:after, .panel-notifications .btn-twitter:after {",
		"	-webkit-filter: invert(100%) hue-rotate(180deg) !important;",
		"}",
		".panel-notifications .btn-facebook:after, .panel-notifications .btn-googleplus:after, .panel-notifications .btn-twitter:after {",
		"	background-color: #222;",
		"	border-radius: 4px;",
		"}",
		".panel-notifications .btn-facebook:hover:after, .panel-notifications .btn-googleplus:hover:after, .panel-notifications .btn-twitter:hover:after {",
		"	-webkit-filter: none !important;",
		"	background-color: #000;",
		"	border-radius: 4px;",
		"}",
		".panel-notifications .btn .label {",
		"	color: #000;",
		"}",
		".notifications-placeholder-social .btn {",
		"	border: 1px solid transparent;",
		"	border-radius: 4px;",
		"	color: #FFF;",
		"	background-color: #0096ff;",
		"	cursor: pointer;",
		"	font-size: 12px;",
		"	margin: 0;",
		"	padding: 7px 12px;",
		"	vertical-align: middle;",
		"	transition-duration: .15s;",
		"	transition-property: background-color, border-color, color, opacity;",
		"}",
		".notifications-placeholder-social .btn:hover {",
		"	background-color: #ff6400;",
		"	color: #fff;",
		"}",
		".panel-notifications .btn-facebook:before, .panel-notifications .btn-googleplus:before, .panel-notifications .btn-twitter:before {",
		"	border-color: transparent;",
		"}",
		".panel-notifications .btn-facebook:hover:before, .panel-notifications .btn-googleplus:hover:before, .panel-notifications .btn-twitter:hover:before {",
		"	border-color: transparent;",
		"}",
		".panel-notifications .btn-googleplus:after {",
		"	content: url(\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMCIgdmlld0JveD0iLTIgLTIgMTYgMTYiPjxwYXRoIGZpbGw9IiM0Mjg1RjQiIGQ9Ik0xMS43NiA2LjEzNmMwLS40MjUtLjAzOC0uODM0LS4xMS0xLjIyN0g2VjcuMjNoMy4yM2EyLjc2IDIuNzYgMCAwIDEtMS4xOTggMS44MXYxLjUwNkg5Ljk3YzEuMTM0LTEuMDQ0IDEuNzg5LTIuNTgyIDEuNzg5LTQuNDF6Ii8+PHBhdGggZmlsbD0iIzM0QTg1MyIgZD0iTTYgMTJjMS42MiAwIDIuOTc4LS41MzcgMy45Ny0xLjQ1NEw4LjAzMyA5LjA0MWMtLjUzNy4zNi0xLjIyNS41NzMtMi4wMzIuNTczLTEuNTYzIDAtMi44ODUtMS4wNTYtMy4zNTctMi40NzRILjYzOHYxLjU1NUE1Ljk5OCA1Ljk5OCAwIDAgMCA2IDEyeiIvPjxwYXRoIGZpbGw9IiNGQkJDMDUiIGQ9Ik0yLjY0MyA3LjE0QTMuNjA3IDMuNjA3IDAgMCAxIDIuNDU1IDZjMC0uMzk1LjA2OC0uNzguMTg4LTEuMTRWMy4zMDVILjYzOGE1Ljk5OCA1Ljk5OCAwIDAgMCAwIDUuMzlMMi42NDMgNy4xNHoiLz48cGF0aCBmaWxsPSIjRUE0MzM1IiBkPSJNNiAyLjM4NmMuODggMCAxLjY3Mi4zMDMgMi4yOTQuODk4bDEuNzItMS43MjFDOC45NzYuNTk1IDcuNjE4IDAgNiAwQTUuOTk4IDUuOTk4IDAgMCAwIC42MzggMy4zMDVMMi42NDMgNC44NkMzLjExNSAzLjQ0MiA0LjQzNyAyLjM4NiA2IDIuMzg2eiIvPjwvc3ZnPg==\");",
		"	height: 30px;",
		"	left: 0px;",
		"	line-height: normal;",
		"	margin-top: 0px;",
		"	top: 0%;",
		"	width: 32px;",
		"}",
		".datagrid-header .datagrid-row {",
		"	background-color: #0a0a0a;",
		"}",
		".c019 {",
		"	color: #FFFFFF;",
		"	background-color: #0096ff;",
		"}",
		".c019:not(.c0115):hover {",
		"	background-color: #ff6400;",
		"}",
		".c0110:not(.c0115).c0114 {",
		"	color: #FFFFFF;",
		"	background-color: #0096ff;",
		"}",
		".c0110 {",
		"	color: #FFFFFF;",
		"	background-color: #0096ff;",
		"}",
		".c0110:not(.c0115):hover {",
		"	background-color: #ff6400;",
		"}",
		".c011 {",
		"	border: 1px solid #333;",
		"}",
		".panel-wrapper .c011 {",
		"	border: 1px solid #ddd;",
		"}",
		".panel-wrapper .c011 .svg-icon {",
		"	fill: black;",
		"}",
		".dropdown-toggle .svg-icon {",
		"	fill: white;",
		"}",
		".c0110:not(.c0115):active, .c0110:not(.c0115):focus {",
		"	background-color: #ff6400;",
		"}",
		".states-button-action.is-active .svg-icon-love {",
		"	fill: #ff1e1e;",
		"}",
		".navbar-item .dropdown-item a, .navbar-item .dropdown-item button {",
		"	-webkit-transition-duration: .15s;",
		"	-webkit-transition-property: background-color,color;",
		"	background-color: #0a0a0a;",
		"	color: #ccc;",
		"}",
		".dropdown .dropdown-menu>li>a:link {",
		"	color: #ccc !important;",
		"}",
		".dropdown .dropdown-menu>li>a:link:hover {",
		"	color: #ff6400 !important;",
		"}",
		".navbar-item .dropdown-menu {",
		"	border: 1px solid #444;",
		"}",
		".navbar-dropdown .navbar-link:hover .svg-icon {",
		"	fill: #0096ff;",
		"}",
		".navbar-dropdown .navbar-link:hover {",
		"	color: #ff6400;",
		"}",
		".navbar-item .dropdown-item:hover a {",
		"	background-color: #222;",
		"}",
		".navbar-item .dropdown-item:active a {",
		"	color: #0096ff;",
		"}",
		"img[src=\"https://e-cdns-images.dzcdn.net/images/misc/d41d8cd98f00b204e9800998ecf8427e/264x264-000000-80-0-0.jpg\"],",
		"img[src=\"https://e-cdns-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/264x264-000000-80-0-0.jpg\"] {",
		"	width: 264px;",
		"	height: 0px;",
		"	/* background-image: url(\'https://storage.cloud.google.com/recubecdn/deezer/img/264x264-000000-80-0-0.jpg\'); */",
		"	background-image: url(\'https://i.imgur.com/TTACVUq.jpg\');",
		"	padding: 0 264px 0 0;",
		"}",
		"img[src=\"https://e-cdns-images.dzcdn.net/images/misc/d41d8cd98f00b204e9800998ecf8427e/100x80-000000-80-0-0.jpg\"],",
		"img[src=\"https://e-cdns-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/100x80-000000-80-0-0.jpg\"] {",
		"	width: 80px;",
		"	height: 0px;",
		"	/* background-image: url(\'https://storage.cloud.google.com/recubecdn/deezer/img/100x80-000000-80-0-0.jpg\'); */",
		"	background-image: url(\'https://i.imgur.com/65YmvX4.jpg\');",
		"	padding: 0 0 100px 0;",
		"}",
		".thumbnail .picture-highlight[style*=\"https://e-cdns-images.dzcdn.net/images/playlist/d41d8cd98f00b204e9800998ecf8427e/200x200-000000-80-0-0.jpg\"] {",
		"	width: 200px;",
		"	height: 0px;",
		"	/* background-image: url(\'https://storage.cloud.google.com/recubecdn/deezer/img/200x200-000000-80-0-0.jpg\') !important; */",
		"	background-image: url(\'https://i.imgur.com/RmfTfQ1.jpg\') !important;",
		"	padding: 0 200px 0 0;",
		"}",
		".thumbnail .picture-img[src*=\"https://e-cdns-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/56x56-000000-80-0-0.jpg\"] {",
		"	width: 56px;",
		"	height: 0px;",
		"	/* background-image: url(\'https://storage.cloud.google.com/recubecdn/deezer/img/56x56-000000-80-0-0.jpg\') !important; */",
		"	background-image: url(\'https://i.imgur.com/WdCaVPb.jpg\') !important;",
		"	padding: 56px 0 0 0;",
		"}",
		".thumbnail .picture.overlay-hidden img[src*=\"https://e-cdns-images.dzcdn.net/images/artist/d41d8cd98f00b204e9800998ecf8427e/86x86-000000-80-0-0.jpg\"] {",
		"	width: 86px;",
		"	height: 0px;",
		"	/* background-image: url(\'https://storage.cloud.google.com/recubecdn/deezer/img/86x86-000000-80-0-0.jpg\') !important; */",
		"	background-image: url(\'https://i.imgur.com/Zddena6.jpg\') !important;",
		"	padding: 86px 0 0 0;",
		"}",
		".thumbnail .picture.overlay-hidden img[src*=\"https://e-cdns-images.dzcdn.net/images/artist/d41d8cd98f00b204e9800998ecf8427e/28x28-000000-80-0-0.jpg\"] {",
		"	width: 28px;",
		"	height: 0px;",
		"	/* background-image: url(\'https://storage.cloud.google.com/recubecdn/deezer/img/28x28-000000-80-0-0.jpg\') !important; */",
		"	background-image: url(\'https://i.imgur.com/CsGmlSh.jpg\') !important;",
		"	padding: 28px 0 0 0;",
		"}",
		".thumbnail .picture-link img[src*=\"https://e-cdns-images.dzcdn.net/images/artist/d41d8cd98f00b204e9800998ecf8427e/264x264-000000-80-0-0.jpg\"], .thumbnail .picture-link img[src*=\"https://e-cdns-images.dzcdn.net/images/user/d41d8cd98f00b204e9800998ecf8427e/264x264-000000-80-0-0.jpg\"] {",
		"	width: 264px;",
		"	height: 0px;",
		"	/* background-image: url(\'https://storage.cloud.google.com/recubecdn/deezer/img/264x264-000000-80-0-0_u.jpg\') !important; */",
		"	background-image: url(\'https://i.imgur.com/1gJpo4Q.jpg\') !important;",
		"	padding: 264px 0 0 0;",
		"}",
		".thumbnail .picture-link img[src*=\"https://e-cdns-images.dzcdn.net/images/artist/d41d8cd98f00b204e9800998ecf8427e/56x56-000000-80-0-0.jpg\"] {",
		"	width: 56px;",
		"	height: 0px;",
		"	/* background-image: url(\'https://storage.cloud.google.com/recubecdn/deezer/img/56x56-000000-80-0-0_u.jpg\') !important; */",
		"	background-image: url(\'https://i.imgur.com/7bUhhDA.jpg\') !important;",
		"	padding: 56px 0 0 0;",
		"}",
		".thumbnail .picture-link img[src*=\"https://e-cdns-images.dzcdn.net/images/artist/d41d8cd98f00b204e9800998ecf8427e/100x80-000000-80-0-0.jpg\"] {",
		"	width: 80px;",
		"	height: 0px;",
		"	/* background-image: url(\'https://storage.cloud.google.com/recubecdn/deezer/img/100x80-000000-80-0-0_u.jpg\') !important; */",
		"	background-image: url(\'https://i.imgur.com/EqQvKxX.jpg\') !important;",
		"	padding: 100px 0 0 0;",
		"}",
		".thumbnail .picture.overlay-hidden img[src*=\"https://e-cdns-images.dzcdn.net/images/user/d41d8cd98f00b204e9800998ecf8427e/32x32-000000-80-0-0.jpg\"] {",
		"	width: 32px;",
		"	height: 0px;",
		"	/* background-image: url(\'https://storage.cloud.google.com/recubecdn/deezer/img/32x32-000000-80-0-0.jpg\') !important; */",
		"	background-image: url(\'https://i.imgur.com/JePY1lo.jpg\') !important;",
		"	padding: 32px 0 0 0;",
		"}",
		"#page_profile .user-section .thumbnail-rounded:hover {",
		"	box-shadow: 0px 0px 3px 1px #0096ff99;",
		"	-webkit-filter: drop-shadow(0px 0px 3px #0096ff99) !important;",
		"	-moz-filter: drop-shadow(0px 0px 3px #0096ff99) !important;",
		"	filter: drop-shadow(0px 0px 3px #0096ff99) !important;",
		"	transition-duration: .15s;",
		"	transition-property: box-shadow, filter, -webkit-filter, -moz-filter;",
		"}",
		"#page_profile .user-section .thumbnail .picture.overlay-hidden:after {",
		"	background-color: #eee;",
		"}",
		"#page_profile .profile-header .header-main .list-actions {",
		"	border-left: 1px solid #343434;",
		"}",
		".datagrid-row.song.active::before, .datagrid-row.song.active + .datagrid-row.song::before {",
		"	background-color: rgba(255, 100, 0, .7);",
		"	transition-duration: .15s;",
		"	transition-property: background-color;",
		"}",
		".datagrid-row.song.active + .datagrid-row:hover.song::before {",
		"	background-color: #333 !important;",
		"	transition-duration: .15s;",
		"	transition-property: background-color;",
		"}",
		".datagrid-header .datagrid-row:hover {",
		"	background-color: #0a0a0a;",
		"}",
		".datagrid-header .datagrid-row::before {",
		"	background-color: transparent;",
		"}",
		".c0113 {",
		"  color: #fff;",
		"  background-color: #E61616;",
		"}",
		".c0113:not(.c0115):hover {",
		"  background-color: #BD2D2D;",
		"}",
		".c0113:not(.c0115):active {",
		"  background-color: #E61616;",
		"}",
		".btn-logout > .c0113 {",
		"	color: #000;",
		"	background-color: #ff9999;",
		"	-webkit-text-stroke: #000 .5px;",
		"}",
		".btn-logout > .c0113:not(.c0115):hover {",
		"	color: #fff;",
		"	background-color: #ff2d2d;",
		"	-webkit-text-stroke: transparent .0px;",
		"}",
		".c0113:not(.c0115):active {",
		"	color: #fff;",
		"	background-color: #ff2d2d;",
		"	-webkit-text-stroke: transparent .0px;",
		"}",
		".form-control::placeholder {",
		"	color: #929292;",
		"}",
		".form-control::-webkit-input-placeholder {",
		"	color: #929292;",
		"}",
		".form-control {",
		"	background-color: #fff;",
		"	border: 1px solid #ddd;",
		"	color: #929292;",
		"}",
		".form-control:focus {",
		"	border-color: #dedede;",
		"}",
		".datagrid-toolbar .toolbar-search .form-control {",
		"	border: 1px solid #dedede;",
		"}",
		"#page_profile .profile-header-container {",
		"	-webkit-box-shadow: none;",
		"	box-shadow: none;",
		"}",
		".datagrid-header .datagrid-row .cell-play:hover {",
		"	-webkit-filter: none !important;",
		"	filter: none !important;",
		"}",
		".page-appstudio .app-header {",
		"	background-color: #0a0a0a;",
		"}",
		".thumbnail-col-app .app-picture {",
		"	border-bottom: 1px solid #343434;",
		"}",
		".page-appstudio .app-filters {",
		"	border-top: 1px solid #343434;",
		"}",
		".thumbnail-col-app .app-meta {",
		"	color: #929292;",
		"}",
		".thumbnail-col-app {",
		"	-webkit-box-shadow: 0px 1px 3px rgba(100, 100, 100, .8);",
		"	box-shadow: 0px 1px 3px 1px rgba(100, 100, 100, .8);",
		"}",
		".thumbnail-col-app:hover {",
		"	-webkit-box-shadow: 0px 1px 3px rgba(0, 150, 255, .8);",
		"	box-shadow: 0px 1px 3px 1px rgba(0, 150, 255, .8);",
		"}",
		".page-appstudio .app-filter-item {",
		"	-webkit-box-shadow: 0px 1px 3px rgba(100, 100, 100, .8);",
		"	box-shadow: 0px 1px 3px 1px rgba(100, 100, 100, .8);",
		"	color: #ccc;",
		"}",
		".page-appstudio .app-filter-item:hover {",
		"	-webkit-box-shadow: 0px 1px 3px rgba(0, 150, 255, .8);",
		"	box-shadow: 0px 1px 3px 1px rgba(0, 150, 255, .8);",
		"	color: #ff6400;",
		"}",
		".page-appstudio .app-filter-item:hover.is-disabled {",
		"	opacity: 1;",
		"}",
		"#modal_sharebox .form-control {",
		"	background-color: #222;",
		"	border: 1px solid #000;",
		"	color: #929292;",
		"}",
		"#modal_playlist_assistant .form-control {",
		"	background-color: #222;",
		"	border: 1px solid #000;",
		"	color: #929292;",
		"}",
		".modal-playlist-assistant .modal-footer:before {",
		"	border-top: 1px solid #000;",
		"}",
		".modal-playlist-assistant .playlist-option {",
		"	color: #0096ff;",
		"}",
		".modal-playlist-assistant .playlist-option-help {",
		"	color: #aaa;",
		"}",
		" #modal_playlist_assistant .playlist-option:hover {",
		"	color: #ff6400;",
		"}",
		"#modal_sharebox .share-friends-form {",
		"	background-color: #0f0f0f;",
		"	border: 1px solid #000000;",
		"}",
		"#modal_sharebox .friend-infos {",
		"	color: #ccc;",
		"}",
		"#modal_sharebox .share-friends-filter:after {",
		"	background-color: #000;",
		"}",
		"#modal_sharebox .friend-item.selected {",
		"	border-color: #0096ff77;",
		"}",
		".slide.layout-dark .slide-btn {",
		"	border-color: #0096ff;",
		"}",
		".slide.layout-dark .slide-btn:hover {",
		"	background-color: #ff6400;",
		"	border-color: #ff6400;",
		"	color: #000000;",
		"}",
		"#page_account .account-wrapper {",
		"	-webkit-box-shadow: none;",
		"	box-shadow: none;",
		"}",
		"#page_account .account-labs {",
		"	-webkit-box-shadow: none;",
		"	box-shadow: none;",
		"}",
		".page-contextmenu .contributor-container .heading-5-sub {",
		"	color: #0096ff;",
		"	text-decoration: underline;",
		"	text-decoration-color: rgba(255, 100, 0, .5);",
		"}",
		".page-contextmenu .heading-5>button {",
		"	color: #222;",
		"	-webkit-text-stroke: #222 .5px;",
		"}",
		".page-contextmenu .heading-5>button:hover {",
		"	color: #ff6400;",
		"	-webkit-text-stroke: #ff6400 .5px;",
		"}",
		".slide.slide-cut .slide-covers:after {",
		"	background-color: #000;",
		"	border-left: 1px solid #000;",
		"}",
		"div.flow-logo > svg > path {",
		"	fill: #0096ff;",
		"}",
		".slide.slide-cut .slide-text .subtitle {",
		"	color: #999;",
		"}",
		".slide.slide-cut .slide-text .label {",
		"	color: #999;",
		"}",
		".slide.slide-cut .slide-background {",
		"	background-color: #000;",
		"}",
		".social-item .c0112 .c012 {",
		"	color: #fff;",
		"}",
		"#modal_edit_personalsong .form-control {",
		"	background-color: #000;",
		"	border: 1px solid #444;",
		"	color: #aaa;",
		"}",
		".c0110:not(.c0124).c0123 {",
		"	color: #fff;",
		"	background-color: #0096ff;",
		"}",
		".thumbnail-col-app {",
		"	border-top-left-radius: 4px;",
		"	border-bottom-right-radius: 4px;",
		"	border-top-right-radius: 4px;",
		"	border-bottom-left-radius: 0;",
		"}"
	].join("\n");
if (false || (document.domain == "deezer.com" || document.domain.substring(document.domain.indexOf(".deezer.com") + 1) == "deezer.com"))
	css += [
		"/* NEW RE-DESIGN - its work in progress and I will probably release it separately or as a customizable part of this style */",
		"",
		".page-electron-sidebar {",
		"	background-color: #191919;",
		"}",
		".page-electron-topbar {",
		"	-webkit-box-shadow: none;",
		"	box-shadow: none;",
		"	background-color: #191919;",
		"}",
		".page-electron-sidebar .sidebar-nav-link:hover {",
		"	background-color: #2f2f2f;",
		"}",
		".popper-content {",
		"	-webkit-box-shadow: 0 2px 10px 0 rgba(225,225,225,.24);",
		"	background-color: #000;",
		"	box-shadow: 0 2px 10px 0 rgba(225, 225, 225,.24);",
		"	color: #aaa;",
		"}",
		".page-electron-topbar .popper-search .search-heading {",
		"	color: #ccc;",
		"}",
		".page-electron-topbar .topbar-search-input {",
		"	background-color: #000000;",
		"	border: 1px solid #333;",
		"	color: #ccc;",
		"}",
		".page-electron-topbar .topbar-search-input::placeholder {",
		"	color: #555;",
		"}",
		".page-electron-topbar .topbar-search-input:focus, .page-electron-topbar .topbar-search-input:hover {",
		"	-webkit-box-shadow: 0 1px 2px 0 rgba(225,225,225,.12);",
		"	background-color: #111;",
		"	box-shadow: 0 1px 2px 0 rgba(225,225,225,.12);",
		"}",
		".page-electron-topbar .topbar-search-input:hover {",
		"	border-color: #0096ff55;",
		"}",
		".page-electron-topbar .topbar-search-active .topbar-search-submit {",
		"	background-color: #0096ff;",
		"	color: #fff;",
		"}",
		".page-electron-topbar .topbar-search-active .topbar-search-submit:hover {",
		"	background-color: #0096ff;",
		"}",
		".page-electron-topbar .topbar-search-input:focus {",
		"	border-color: #0096ff;",
		"}",
		".page-electron-topbar .popper-search .nano-card-item {",
		"	background-color: #121212;",
		"}",
		".page-electron-topbar .popper-search .nano-card-item:hover {",
		"	background-color: #2f2f2f;",
		"}",
		".popper[x-placement=bottom] .popper-arrow {",
		"	border-bottom-color: #000;",
		"}",
		".page-electron-topbar .popper-account .account-heading {",
		"	color: #ccc;",
		"}",
		".page-electron-topbar .popper-account .account-header:hover {",
		"	background-color: #111;",
		"}",
		".page-electron-topbar .popper-account .account-link.is-main {",
		"	color: #ccc;",
		"}",
		".page-electron-topbar .popper-account .account-link:hover {",
		"	background-color: #2f2f2f;",
		"}",
		".page-electron-topbar .popper-account .account-link {",
		"	color: #ccc;",
		"}",
		".page-electron-topbar .topbar-notification:hover {",
		"	background-color: #ff6400;",
		"}",
		"#page_topbar > div.popper-wrapper.topbar-entrypoints > a[data-type=\"offers_subscribe\"] > span {",
		"	color: #ccc !important;",
		"}",
		".page-electron-topbar .popper-entrypoints {",
		"	color: #aaa;",
		"}",
		".page-electron-topbar .popper-account .account-menu {",
		"	border-top: 1px solid #333;",
		"}",
		".page-electron-topbar .popper-account .account-item.is-divider {",
		"	border-top: 1px solid #333;",
		"}",
		".page-player .player-bottom {",
		"	-webkit-box-shadow: 0 -1px 12px 0 rgba(225,225,225,.12);",
		"	background-color: #0a0a0a;",
		"	box-shadow: 0 -1px 12px 0 rgba(225,225,225,.12);",
		"}",
		".player-controls .svg-icon-group-btn, .player-track .svg-icon-group-btn, .player-options .svg-icon-group-btn {",
		"	color: #aaa;",
		"}",
		".player-controls .svg-icon-group-btn.is-active, .player-controls .svg-icon-group-btn:hover, .player-track .svg-icon-group-btn.is-active, .player-track .svg-icon-group-btn:hover, .player-options .svg-icon-group-btn.is-active, .player-options .svg-icon-group-btn:hover  {",
		"	background-color: #0096ff;",
		"	color: #fff",
		"}",
		".page-player .player-options .option-item+.option-item:before {",
		"	background-color: #333;",
		"}",
		".page-player .popper-player-preview .preview-link {",
		"	color: #aaa;",
		"}",
		".popper[x-placement=top] .popper-arrow {",
		"	border-top-color: #000;",
		"}",
		".page-player .player-options .queuelist-label {",
		"	color: #aaa;",
		"}",
		".page-player .player-options .queuelist.is-available:hover {",
		"	background-color: #2f2f2f;",
		"	-webkit-box-shadow: 0px 0px 3px 1px #0096ff, inset 0px 0px 0px 1px #999;",
		"	box-shadow: 0px 0px 3px 1px #0096ff, inset 0px 0px 0px 1px #999;",
		"}",
		".page-player .player-options .queuelist.is-active {",
		"	background-color: #2f2f2f;",
		"	-webkit-box-shadow: 0px 0px 3px 1px #ff6400, inset 0px 0px 0px 1px #999;",
		"	box-shadow: 0px 0px 3px 1px #ff6400, inset 0px 0px 0px 1px #999;",
		"}",
		".page-player .player-options .queuelist {",
		"	-webkit-transition-property: background-color, box-shadow, -webkit-box-shadow;",
		"	transition-property: background-color, box-shadow, -webkit-box-shadow;",
		"}",
		".page-player .player-options .queuelist.is-active .queuelist-label, .page-player .player-options .queuelist.is-available:hover .queuelist-label {",
		"	color: #0096ff;",
		"}",
		".page-player .popper-player-settings .setting-label {",
		"	color: #aaa;",
		"}",
		".page-player .popper-player-settings .setting-info {",
		"	color: #ff6400;",
		"}",
		".input-switch {",
		"	background-color: #222;",
		"}",
		".input-switch.is-checked {",
		"	background-color: #444;",
		"}",
		".input-switch.is-checked:after {",
		"	background-color: #0096ff;",
		"}",
		".input-radio.is-checked:after {",
		"	background-color: #0096ff;",
		"}",
		".page-player .popper-player-settings .setting-menu+.setting-menu {",
		"	border-top: 1px solid #333;",
		"}",
		".page-player .player-full {",
		"	background-color: #0a0a0a;",
		"}",
		".page-player .queuelist-title {",
		"	color: #aaa;",
		"}",
		".page-player .queuelist-subtitle {",
		"	color: #ccc;",
		"}",
		".page-electron-topbar .popper-search .search-suggest-view-link {",
		"	color: #aaa;",
		"}",
		".page-electron-topbar .popper-search .search-suggest-view-all {",
		"	border-top: 1px solid #333;",
		"}",
		".page-electron-sidebar .sidebar-nav-item.is-divider {",
		"	border-top: 1px solid #333;",
		"}",
		".slider-tooltip {",
		"	color: #ccc;",
		"	background-color: #333;",
		"}",
		".slider-track-input::-webkit-slider-thumb {",
		"	-webkit-box-shadow: 0 0 1px 0 rgba(225,225,225,.48);",
		"	background-color: #ff6400;",
		"	border: 1px solid #000000;",
		"	box-shadow: 0 0 1px 0 rgba(225,225,225,.48);",
		"}",
		".slider-track-input::-moz-range-thumb {",
		"	background-color: #ff6400;",
		"	border: 1px solid #000;",
		"	box-shadow: 0 0 1px 0 rgba(225,225,225,.48);",
		"}",
		".slider-track-default {",
		"	background-color: #898989;",
		"}",
		".slider-track-active {",
		"	background-color: #0096ff;",
		"}",
		".page-player .queuelist-header {",
		"	border-bottom: 1px solid #333;",
		"	box-shadow: 0px 1px 0px 0px #0096ff, inset 0px -1px 0px 0px #cccb;",
		"	z-index: 100;",
		"}",
		".svg-icon-group-btn {",
		"	color: #ccc;",
		"}",
		".player-container .svg-icon-group-btn:hover {",
		"	color: #fff;",
		"}",
		".player-close .svg-icon-group-btn:hover {",
		"	color: #fff;",
		"}",
		".page-player .queuelist-cover-title {",
		"	color: #ccc;",
		"}",
		".page-electron-topbar .popper-notifications .notifications-placeholder-title {",
		"	color: #ccc;",
		"}",
		".page-electron-topbar .popper-notifications .popper-navbar-link.active {",
		"	background-color: #2f2f2f;",
		"	color: #0096ff;",
		"}",
		".page-electron-topbar .popper-notifications .popper-navbar {",
		"	border-bottom: 1px solid #333;",
		"}",
		".page-electron-topbar .popper-notifications .popper-navbar-link {",
		"	color: #aaa;",
		"}",
		".page-electron-topbar .popper-notifications .popper-navbar-link:hover {",
		"	background-color: #777;",
		"	color: #333;",
		"}",
		".page-electron-topbar .popper-notifications .popper-navbar-item+.popper-navbar-item {",
		"	border-left: 1px solid #333;",
		"}",
		".page-electron-topbar .popper-notifications .notifications-item:hover {",
		"	background-color: #2f2f2f;",
		"}",
		".page-electron-topbar .popper-notifications .popper-headings .filter-control.form-control {",
		"	background-color: #000;",
		"	border: 1px solid #333;",
		"	color: #929292;",
		"}",
		".page-electron-topbar .popper-notifications .popper-headings .filter-control {",
		"	color: #aaa;",
		"}",
		".page-electron-topbar .popper-notifications .notifications-item {",
		"	border-bottom: 1px solid #333333;",
		"}",
		".page-player .player-track .track-heading {",
		"	color: #ccc;",
		"}",
		"#page_account .account-delete-btn {",
		"	color: #ff0000;",
		"}",
		"#page_account .account-delete-btn:hover {",
		"	color: #fff !important;",
		"	-webkit-filter: drop-shadow(0 0 5px #ff0000) drop-shadow(0 0 1px #ff0000) drop-shadow(0 0 3px #ff0000) !important;",
		"	filter: drop-shadow(0 0 5px #ff0000) drop-shadow(0 0 1px #ff0000) drop-shadow(0 0 3px #ff0000) !important;",
		"	font-weight: bold;",
		"	transition-property: font-weight, filter, -webkit-filter, color;",
		"	transition-duration: 0.15s;",
		"	transition-timing-function: ease-in-out;",
		"}",
		".page-electron-topbar .popper-search .search-history-link {",
		"	color: #aaa;",
		"}",
		".page-electron-topbar .popper-search .search-history-link:hover {",
		"	background-color: #222;",
		"}",
		".page-electron-topbar .popper-search .search-heading-button {",
		"	color: #aaa;",
		"}",
		".page-electron-topbar .popper-search .search-heading-button:hover {",
		"	color: #ff6400;",
		"}",
		".page-topbar {",
		"	-webkit-box-shadow: 0px 5px 4px -3px rgba(255,255,255,.12);",
		"	background-color: #0f0f0f;",
		"	box-shadow: 0px 5px 4px -3px rgba(255,255,255,.12);",
		"}",
		".page-topbar .topbar-search-input {",
		"	background-color: #000000;",
		"	border: 1px solid #232323;",
		"	color: #aaa;",
		"}",
		".page-topbar .topbar-search-input:focus, .page-topbar .topbar-search-input:hover {",
		"	-webkit-box-shadow: 0 1px 2px 0 rgba(255,255,255,.12);",
		"	background-color: #000;",
		"	box-shadow: 0 1px 2px 0 rgba(255,255,255,.12);",
		"}",
		".page-topbar .topbar-search-input:hover {",
		"	border-color: #636363;",
		"}",
		".page-topbar .topbar-search-input::-webkit-input-placeholder, .page-topbar .topbar-search-input::placeholder {",
		"	color: #929292;",
		"}",
		".page-topbar .topbar-search-input:focus::-webkit-input-placeholder, .page-topbar .topbar-search-input:focus::placeholder {",
		"	color: #444;",
		"}",
		".page-topbar .topbar-search-submit {",
		"	color: #929292;",
		"}",
		".page-topbar .topbar-search-clear {",
		"	color: #929292;",
		"}",
		".page-topbar .topbar-search-input:focus {",
		"	border-color: #0096ff;",
		"}",
		".page-topbar .popper-search .search-heading {",
		"	color: #ccc;",
		"}",
		".page-topbar .topbar-search-active .topbar-search-clear:hover {",
		"	color: #ff6400;",
		"}",
		".page-topbar .popper-search .nano-card-item {",
		"	background-color: #111;",
		"}",
		".page-topbar .popper-search .nano-card-item:hover {",
		"	background-color: #333;",
		"}",
		".page-topbar .topbar-search-active .topbar-search-submit {",
		"	background-color: #0096ff;",
		"	color: #fff;",
		"}",
		".page-topbar .popper-search .search-history-link:hover {",
		"	background-color: #222;",
		"}",
		".page-sidebar .sidebar-nav-link:hover {",
		"	background-color: #333;",
		"}",
		".page-topbar .topbar-notification:hover {",
		"	background-color: #0096ff;",
		"}",
		".page-topbar .popper-notifications .popper-navbar-link.active {",
		"	background-color: #333;",
		"	color: #0096ff;",
		"}",
		".page-topbar .popper-notifications .popper-navbar {",
		"	border-bottom: 1px solid #333;",
		"}",
		".page-topbar .popper-notifications .popper-navbar-item+.popper-navbar-item {",
		"	border-left: 1px solid #333;",
		"}",
		".page-topbar .popper-notifications .popper-navbar-link:hover {",
		"	background-color: #666;",
		"}",
		".page-topbar .popper-notifications .popper-navbar-link:hover {",
		"	background-color: #666;",
		"	color: #32323d;",
		"}",
		".page-topbar .popper-notifications .notifications-item {",
		"	border-bottom: 1px solid #222;",
		"}",
		".page-topbar .popper-notifications .notifications-placeholder-title {",
		"	color: #ccc;",
		"}",
		".page-topbar .popper-notifications .notifications-placeholder-text {",
		"	color: #777;",
		"}",
		".page-topbar .popper-notifications .popper-headings .filter-control {",
		"	color: #666;",
		"}",
		".page-topbar .popper-notifications .popper-headings .form-control {",
		"	background-color: #000;",
		"	border: 1px solid #232323;",
		"	color: #ccc;",
		"}",
		".page-topbar .popper-account .account-heading {",
		"	color: #ccc;",
		"}",
		".page-topbar .popper-account .account-link.is-main {",
		"	color: #aaa;",
		"}",
		".page-topbar .popper-account .account-header:hover {",
		"	background-color: #333;",
		"}",
		".page-topbar .popper-account .account-menu {",
		"	border-top: 1px solid #333;",
		"}",
		".page-topbar .popper-account .account-item.is-divider {",
		"	border-top: 1px solid #333;",
		"}",
		".page-topbar .popper-account .account-link:hover {",
		"	background-color: #333;",
		"}",
		".page-topbar .popper-account .account-link {",
		"	color: #aaa;",
		"}",
		".page-topbar .popper-search .search-heading-button {",
		"	color: #999;",
		"}",
		".page-topbar .popper-search .search-heading-button:hover {",
		"	color: #ff6400;",
		"}",
		".page-topbar .popper-search .search-suggest-view-link {",
		"	color: #aaa;",
		"}",
		".page-topbar .popper-search .search-suggest-view-all {",
		"	border-top: 1px solid #333;",
		"}",
		".page-topbar .popper-search .search-history-link {",
		"	color: #666;",
		"}",
		".form-control:focus::-webkit-input-placeholder, .form-control:focus::placeholder {",
		"	color: #444;",
		"}",
		".form-control::-webkit-input-placeholder, .form-control::placeholder {",
		"	color: #929292;",
		"}",
		".datagrid-toolbar .toolbar-search .form-control:focus::-webkit-input-placeholder, .datagrid-toolbar .toolbar-search .form-control:focus::placeholder,",
		".catalog-tab-comment .post-comment .form-control:focus::-webkit-input-placeholder, .catalog-tab-comment .post-comment .form-control:focus::placeholder,",
		"#page_profile .user-search .form-control:focus::-webkit-input-placeholder, #page_profile .user-search .form-control:focus::placeholder {",
		"	color: #d1d1d1;",
		"}",
		".page-contextmenu .menu-item>.icon {",
		"	color: #929292;",
		"}",
		".page-topbar .popper-notifications .notifications-item:hover {",
		"	background-color: #333;",
		"}",
		".btn-tag-400:hover.selected, .btn-tag-600:hover.selected, .btn-tag-800:hover.selected {",
		"	background-color: #ff6400;",
		"	color: #fff;",
		"}",
		".btn-tag-400.selected, .btn-tag-600.selected, .btn-tag-800.selected {",
		"	background-color: #0096ff;",
		"	color: #000;",
		"}",
		".btn-tag-400.selected .tag-action, .btn-tag-600.selected .tag-action, .btn-tag-800.selected .tag-action {",
		"	border-left: 1px solid rgba(0, 0, 0, 0.2);",
		"	color: #000;",
		"}",
		".btn-tag-400.selected .tag-action:hover, .btn-tag-600.selected .tag-action:hover, .btn-tag-800.selected .tag-action:hover {",
		"	background-color: #ff6400;",
		"	color: #fff;",
		"}",
		".btn-tag-400 .tag-action:hover, .btn-tag-600 .tag-action:hover, .btn-tag-800 .tag-action:hover {",
		"	background-color: #ff6400;",
		"	color: #fff;",
		"}",
		".btn-tag-400:hover.selectable, .btn-tag-600:hover.selectable, .btn-tag-800:hover.selectable {",
		"	background-color: #ff6400;",
		"	color: #fff;",
		"}",
		".btn-tag-400 .tag-action, .btn-tag-600 .tag-action, .btn-tag-800 .tag-action  {",
		"	border-left: 1px solid rgba(0, 0, 0, 0.2);",
		"	color: #000;",
		"}",
		".btn-tag .tag-action {",
		"	margin: -8px -13px 0 12px;",
		"}",
		".svg-icon-group-btn.is-active, .svg-icon-group-btn:hover {",
		"	background-color: #ff6400;",
		"}",
		".svg-icon-group-btn:active {",
		"	background-color: #0096ff;",
		"}",
		".page-topbar .topbar-notification svg.svg-icon.svg-icon-bell {",
		"	-webkit-transition-duration: 1s;",
		"	-webkit-transition-property: fill;",
		"	transition-duration: 1s;",
		"	transition-property: fill;",
		"}",
		"svg.svg-icon.svg-icon-bell {",
		"	fill: #aaa;",
		"}",
		".page-topbar .topbar-notification:hover svg.svg-icon.svg-icon-bell {",
		"	fill: #fff;",
		"}",
		".marquee-gradient-right {",
		"	background-image: -webkit-gradient(linear,left top,right top,from(hsla(0,0%,100%,0)),to(#000));",
		"	background-image: linear-gradient(90deg,hsla(0,0%,100%,0),#000);",
		"	right: 0;",
		"}",
		".marquee-gradient-left {",
		"	background-image: -webkit-gradient(linear,left top,right top,from(#000),to(hsla(0,0%,100%,0)));",
		"	background-image: linear-gradient(90deg,#000,hsla(0,0%,100%,0));",
		"	left: 0;",
		"}",
		".slide .slide-btn {",
		"    color: #eee !important;",
		"}",
		".slide .slide-btn:hover {",
		"    color: #fff !important;",
		"}",
		".navbar-link {",
		"    display: -moz-inline-box;",
		"}",
		".navbar-nav > li > a, .navbar-nav > li > button {",
		"	display: -moz-inline-box;",
		"}",
		".c011.c019 .c012 {",
		"	color: #fff;",
		"}"
	].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
