// ==UserScript==
// @name          Scrollbars figuccio
// @description	  scrollbars for Chrome. Scrollbar up and down buttons are forced to always appear.
// @author        figuccio
// @run-at        document-start
// @include	*
// @version       0.1
// @namespace https://greasyfork.org/users/237458
// ==/UserScript==
(function() {var css = "";
if (false || (new RegExp("^https?://.*$")).test(document.location.href))
	css += [
		".resize-grip {",
		"    background: linear-gradient(-45deg, transparent 2px, hsl(0, 0%, 40%) 2px, transparent 3px, transparent 4.5px, hsl(0, 0%, 40%) 5px, transparent 5.5px)!important;",
		"}",
		"",
		"/* Browser */",
		"::-webkit-scrollbar {",
		"    background: deepskyblue!important;",
		"    border: thin solid hsl(0, 0%, 20%)!important;",
		"    display: initial!important;",
		"    height: 13px!important;",
		"    max-height: 13px!important;",
		"    max-width: 13px!important;",
		"    min-height: 13px!important;",
		"    min-width: 15px!important;",
		"    padding: 0!important;",
		"    width: 13px!important;",
		"}",
		"::-webkit-scrollbar-button {",
		"    display: none!important;",
		"}",
		"::-webkit-scrollbar-button:single-button {",
		"    border: thin solid green!important;",
		"    display: block!important;",
		"    height: 13px!important;",
		"    margin: 0!important;",
		"    max-height: 13px!important;",
		"    max-width: 13px!important;",
		"    min-height: 15px!important;",
		"    min-width: 13px!important;",
		"    width: 13px!important;",
		"}",
		"::-webkit-scrollbar-button:horizontal:decrement {",
		"    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAANCAYAAABy6+R8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgFDhoaUbP33wAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAdElEQVQoz83SsQ1BARQF0BudsILeBDoxiTns8EtT2OLHBDoVDZFI9BqRo1AQUbxfcet3invzkr8Ihph2AWM02FTBHGtccKiAJbaeuWNXQSevXLH/vOl9cU2SNsktST+JaqcZVjjj2GW9ERbl9d7gAJPffcoD60Zo/GBzO+QAAAAASUVORK5CYII=)!important;",
		"    background-size: cover!important;",
		"    background-repeat: no-repeat!important;",
		"    background-color: green!important;",
		"    border-bottom-right-radius: 3px!important;",
		"    border-top-right-radius: 3px!important;",
		"}",
		"::-webkit-scrollbar-button:horizontal:decrement:active {",
		"    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAANCAYAAABy6+R8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgFDhs56s+37AAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAd0lEQVQoz83SsQnCUBQF0AMWFskI2meCdJJJnCM7WGYK13CCdKlikyAIgqVdSJpvIwH/r/Q2r3mHB5fHvyTHIQUUOKGNBUdc8MAQAxp0mDGhj0G3AGa8cP1c2KygCVvswnyG619T4Yw7xpT29qhT2nsnQ/m7N1kACdwUrJ0jQzwAAAAASUVORK5CYII=)!important;",
		"    background-color: !important;",
		"}",
		"::-webkit-scrollbar-button:horizontal:decrement:not(:active):hover {",
		"    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAANCAYAAABy6+R8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgFDhs56s+37AAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAd0lEQVQoz83SsQnCUBQF0AMWFskI2meCdJJJnCM7WGYK13CCdKlikyAIgqVdSJpvIwH/r/Q2r3mHB5fHvyTHIQUUOKGNBUdc8MAQAxp0mDGhj0G3AGa8cP1c2KygCVvswnyG619T4Yw7xpT29qhT2nsnQ/m7N1kACdwUrJ0jQzwAAAAASUVORK5CYII=)!important;",
		"    background-color: yellow!important;",
		"}",
		"::-webkit-scrollbar-button:horizontal:increment {",
		"    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAANCAYAAABy6+R8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgFDhMBChSFegAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAdElEQVQoz83QIQoCUQCE4QmCQa9g9wQ28SSeYaN38CQeYlnwBEaLFmVBsBssn0FBEMN7Sf80YX4GJvkZmGFUK+2wwqRGOuOCDRal0sGTOzo0JdIRN2/6z87gm5dk+Mr7JG3J0glXbLGseW+Nac17c4zzFzwANftoDW4riZUAAAAASUVORK5CYII=)!important;",
		"    background-size: cover!important;",
		"    background-repeat: no-repeat!important;",
		"    background-color:green !important;",
		"    border-bottom-left-radius: 3px!important;",
		"    border-top-left-radius: 3px!important;",
		"}",
		"::-webkit-scrollbar-button:horizontal:increment:active {",
		"    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAANCAYAAABy6+R8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgFDhUjiS5jGAAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAeUlEQVQoz83RsQnCcBTE4Q8UBHWQTGAnTpIZ3COTOEDKEMgEljbaJAQEOwsLm3+aVBLCs9KrHsf9OI7HL7XDZi6wmPBKrNHiGW3qcMcJhyh0RcIbNY4R6IbXCCb0n4HlBJSwGu8LqkhTiwca5NFNZxTIvvnTHlt/oQHnWRWTSdNqYQAAAABJRU5ErkJggg==)!important;",
		"    background-color: !important;",
		"}",
		"::-webkit-scrollbar-button:horizontal:increment:not(:active):hover {",
		"    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAANCAYAAABy6+R8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgFDhUjiS5jGAAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAeUlEQVQoz83RsQnCcBTE4Q8UBHWQTGAnTpIZ3COTOEDKEMgEljbaJAQEOwsLm3+aVBLCs9KrHsf9OI7HL7XDZi6wmPBKrNHiGW3qcMcJhyh0RcIbNY4R6IbXCCb0n4HlBJSwGu8LqkhTiwca5NFNZxTIvvnTHlt/oQHnWRWTSdNqYQAAAABJRU5ErkJggg==)!important;",
		"    background-color: yellow!important;",
		"}",
		"::-webkit-scrollbar-button:vertical:decrement {",
		"    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAANCAYAAABy6+R8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgFDgonQxmpnwAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAc0lEQVQoz+XRMUoCAACF4Q/BSa/gHjl1Alu8QwguXcC7eApPIXQJt2iKjhAk+DcoJDjonP/8vulxJ1Wr6rNa3wpm1bZju2p5DUyqTfXTX2/Vw/lucAZGWOAZQ3zjgEe8VuMLhClesMc7vvBxwnM8/ecffwFSoEVS/hyFWgAAAABJRU5ErkJggg==)!important;",
		"    background-size: cover!important;",
		"    background-repeat: no-repeat!important;",
		"    background-color: green!important;",
		"    border-bottom-left-radius: 3px!important;",
		"    border-bottom-right-radius: 3px!important;",
		"}",
		"::-webkit-scrollbar-button:vertical:decrement:active {",
		"    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAANCAYAAABy6+R8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgFDgo6IB/FRgAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAc0lEQVQoz+XRoQ2DYBiE4YfUkEDqEfW1TNA5EFUdAM0aTNEpSKqwKAZogkJgmpDUgPkFqFa3py757r1PHP+jEgPqb4ELGizocf0EnHDHO0ALHjhvQ4eNT3BDgSPmcE8RoQ1lOyhHhRgjXpjCtwwdnr864go2lhOp4XYeZgAAAABJRU5ErkJggg==)!important;",
		"    background-color: !important;",
		"}",
		"::-webkit-scrollbar-button:vertical:decrement:not(:active):hover {",
		"    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAANCAYAAABy6+R8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgFDgo6IB/FRgAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAc0lEQVQoz+XRoQ2DYBiE4YfUkEDqEfW1TNA5EFUdAM0aTNEpSKqwKAZogkJgmpDUgPkFqFa3py757r1PHP+jEgPqb4ELGizocf0EnHDHO0ALHjhvQ4eNT3BDgSPmcE8RoQ1lOyhHhRgjXpjCtwwdnr864go2lhOp4XYeZgAAAABJRU5ErkJggg==)!important;",
		"    background-color:yellow !important;",
		"}",
		"::-webkit-scrollbar-button:vertical:increment {",
		"    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAANCAYAAABy6+R8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgFDTUIslAAowAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAdUlEQVQoz+XPIQoCUQCE4XnJ4Daz3UuIJ9lsNHoH457CUwhWD+ANBEGzYUG+Da6IsIhZ/zQwDDOT/B7lKTBP0iSZJGl7T5JRkmuSZSnl8JZGhQ0uuOPmwRlrjAdrMcPeixZbTD/uRY1jH9ph8dVRNDhhlT+hA0tUX1KVJjAXAAAAAElFTkSuQmCC)!important;",
		"    background-size: cover!important;",
		"    background-repeat: no-repeat!important;",
		"    background-color:green !important;",
		"    border-top-left-radius: 3px!important;",
		"    border-top-right-radius: 3px!important;",
		"}",
		"::-webkit-scrollbar-button:vertical:increment:active {",
		"    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAANCAYAAABy6+R8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgFDgUlKo/UfAAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAaUlEQVQoz+XPsQmDUAAE0NfHFdI7gZ1kEmdI6Q6WTuEUQiZIl8o0CYGAvYUg3+aXitZ6zcFxx91xbOR44oMO78jfqGdLoQQVekwYEPBHictaW4pHNAeMaHDdmlngFUMtbnv/1fjh7iSYAfRHFgTlUa3mAAAAAElFTkSuQmCC)!important;",
		"    background-color: !important;",
		"}",
		"::-webkit-scrollbar-button:vertical:increment:not(:active):hover {",
		"    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAANCAYAAABy6+R8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgFDgUlKo/UfAAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAaUlEQVQoz+XPsQmDUAAE0NfHFdI7gZ1kEmdI6Q6WTuEUQiZIl8o0CYGAvYUg3+aXitZ6zcFxx91xbOR44oMO78jfqGdLoQQVekwYEPBHictaW4pHNAeMaHDdmlngFUMtbnv/1fjh7iSYAfRHFgTlUa3mAAAAAElFTkSuQmCC)!important;",
		"    background-color: yellow!important;",
		"}",
		"::-webkit-scrollbar-corner {",
		"    background: #FFFF00!important;",
		"    border: 0!important;",
		"}",
		"::-webkit-scrollbar-thumb {",
		"    background: red!important;",
		"    background-clip: content-box!important;",
		"    border: solid transparent!important;",
		"    border-radius: 13px!important;",
		"    box-shadow: inset 0 0 0 1px hsl(0, 0%, 42%)!important;",
		"}",
		"::-webkit-scrollbar-thumb:active {",
		"    background: !important;",
		"    background-clip: content-box!important;",
		"    box-shadow: inset 0 0 0 1px hsl(0, 0%, 58%)!important;",
		"    transition: none!important;",
		"}",
		"::-webkit-scrollbar-thumb:horizontal {",
		"    border-width: 2px 0!important;",
		"}",
		"::-webkit-scrollbar-thumb:not(:active):hover {",
		"    background: !important;",
		"    background-clip: content-box!important;",
		"    box-shadow: inset 0 0 0 1px hsl(0, 0%, 50%)!important;",
		"}",
		"::-webkit-scrollbar:disabled,",
		"::-webkit-scrollbar-thumb:vertical {",
		"    border-width: 0 2px!important;",
		"}",
		"::-webkit-scrollbar:disabled,",
		"::-webkit-scrollbar-button:single-button:disabled,",
		"::-webkit-scrollbar-track,",
		"::-webkit-scrollbar-track-piece {",
		"    visibility: hidden!important;",
		"}",
		"/* 110% zoom*/",
		"@media (min-resolution: 1.1dppx) {",
		"::-webkit-scrollbar, ::-webkit-scrollbar-button:single-button {",
		"    height: 12px!important;",
		"    max-height: 12px!important;",
		"    max-width: 12px!important;",
		"    min-height: 12px!important;",
		"    min-width: 12px!important;",
		"    width: 12px!important;",
		"}",
		"::-webkit-scrollbar:disabled,",
		"::-webkit-scrollbar-thumb:vertical {",
		"    border-width: 0 1.818px!important;",
		"}",
		"::-webkit-scrollbar-thumb:horizontal {",
		"    border-width: 1.818px 0!important;",
		"}",
		".CodeMirror-hscrollbar {",
		"    height: 12px!important;",
		"    max-height: 12px!important;",
		"    min-height: 12px!important;",
		"}",
		".CodeMirror-hscrollbar[style*=\"display: block;\"] {",
		"    right: 12px!important;",
		"}",
		".CodeMirror-vscrollbar {",
		"    max-width: 12px!important;",
		"    min-width: 12px!important;",
		"    width: 12px!important;",
		"}",
		".CodeMirror-vscrollbar[style*=\"margin-bottom: 0px;\"] {",
		"    bottom: 12px!important;",
		"}",
		"}",
		"/* 125% zoom*/",
		"@media (min-resolution: 1.25dppx) {",
		"::-webkit-scrollbar, ::-webkit-scrollbar-button:single-button {",
		"    height: 11px!important;",
		"    max-height: 11px!important;",
		"    max-width: 11px!important;",
		"    min-height: 11px!important;",
		"    min-width: 11px!important;",
		"    width: 11px!important;",
		"}",
		"::-webkit-scrollbar:disabled,",
		"::-webkit-scrollbar-thumb:vertical {",
		"    border-width: 0 1.6px!important;",
		"}",
		"::-webkit-scrollbar-thumb:horizontal {",
		"    border-width: 1.6px 0!important;",
		"}",
		".CodeMirror-hscrollbar {",
		"    height: 11px!important;",
		"    max-height: 11px!important;",
		"    min-height: 11px!important;",
		"}",
		".CodeMirror-hscrollbar[style*=\"display: block;\"] {",
		"    right: 11px!important;",
		"}",
		".CodeMirror-vscrollbar {",
		"    max-width: 11px!important;",
		"    min-width: 11px!important;",
		"    width: 11px!important;",
		"}",
		".CodeMirror-vscrollbar[style*=\"margin-bottom: 0px;\"] {",
		"    bottom: 11px!important;",
		"}",
		"}",
		"/* 150% zoom*/",
		"@media (min-resolution: 1.5dppx) {",
		"::-webkit-scrollbar, ::-webkit-scrollbar-button:single-button {",
		"    height: 9px!important;",
		"    max-height: 9px!important;",
		"    max-width: 9px!important;",
		"    min-height: 9px!important;",
		"    min-width: 9px!important;",
		"    width: 9px!important;",
		"}",
		"::-webkit-scrollbar:disabled,",
		"::-webkit-scrollbar-thumb:vertical {",
		"    border-width: 0 1.333px!important;",
		"}",
		"::-webkit-scrollbar-thumb:horizontal {",
		"    border-width: 1.333px 0!important;",
		"}",
		".CodeMirror-hscrollbar {",
		"    height: 9px!important;",
		"    max-height: 9px!important;",
		"    min-height: 9px!important;",
		"}",
		".CodeMirror-hscrollbar[style*=\"display: block;\"] {",
		"    right: 9px!important;",
		"}",
		".CodeMirror-vscrollbar {",
		"    max-width: 9px!important;",
		"    min-width: 9px!important;",
		"    width: 9px!important;",
		"}",
		".CodeMirror-vscrollbar[style*=\"margin-bottom: 0px;\"] {",
		"    bottom: 9px!important;",
		"}",
		"}"
	].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
